OutSystems/outsystems-ui

gulp/ProjectSpecs/DefaultSpecs.js
package-lock.json
package.json
src/scripts/OSFramework/Constants.ts
src/scss/OutSystemsUI.scss

This PR is for update OSUI version in dev.

Code freeze: Update OSUI version

---

gulp/ProjectSpecs/DefaultSpecs.js
gulp/Tasks/UpdateVersion.js
gulp/tasks/CreateScss/SectionIndex.js
gulp/tasks/TsTanspile.js
gulpfile.js
package-lock.json
package.json
src/scss/OutSystemsUI.scss

This PR is for:
- Adding the updateVersion npm script to the repository, and from now on in order to update repository version the "**npm run update-version**";
- Also improved and added OSUI library version to the compiles JS and CSS files.

[ROU-4014] - PR2 - Adding repo improvements.

---

.github/workflows/dev.yml

This PR is for GitHub action changes to point to main.

GitHub action changes to point to main.

---

.github/workflows/dev.yml

This PR is to GitHub action changes2

GitHub action changes2

---

src/scripts/OSFramework/OSUI/Helper/Device.ts

This PR is for is to update the iPhone dimensions on OSUi framework.

ROU-4074: Latest iPhone dimensions to the framework

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This PR is to fix DropdownServerSide inside BottomSheet and Sidebar, by adjusting the z-index value.

ROU-4102: Fix DropdownServerSide inside BottomSheet and Sidebar

---

src/scripts/Providers/OSUI/Carousel/Splide/Splide.ts

This PR is for improving Carousel pattern internal methods.
- We did an analysis to the load of carousel, and detect two long task. After studying the code we can't change it that much, but we can prevent it to run too many times. 
- simplify long tasks;

ROU-4059 - [OSUI] - Improve JS Long Tasks on Carousel UI Pattern

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This PR is for adding fixes for the DropdownServerSide inside the popup and Notification.

ROU-4102: fix serverside pattern inside popup and notification

---

src/scripts/OSFramework/OSUI/Event/EventEnum.ts
src/scripts/OSFramework/OSUI/Event/EventManager.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Events.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/scss/_submenu.scss

This PR is for fixing the behavior of Submenu on Sidemenu and fix CSS issues when has multiple submenus. Check the JIRA issue for more information.

ROU-4044: Review Submenu behavior and fix multilevel menu

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/Utils.ts

This PR is for adding the new parameters to extensibility configurations.

ROU-4100: Add new support extensibility parameters to range slider

---

src/scripts/OSFramework/OSUI/Pattern/BottomSheet/scss/_bottomsheet.scss
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR will fix an issue related with **DatePicker**, **DateRange**, **MonthPicker** and **TimePicker** when inside a bottom sheet, due to a position issue.

[ROU-4005] - Date, DateRange, Month and Time pickers fixed issue

---

CODEOWNERS
dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
package.json
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/NoUiSliderEnum.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/README.md

Update NoUiSlider to version 15.7.0
This PR is to update NoUiSlider library version to v15.7.0

Update NoUiSlider to version 15.7.0

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/ErrorCodes.ts
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Callbacks.ts
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/Sidebar/ISidebar.ts
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/SidebarAPI.ts

This PR is for adding the OnInitialize event and ClickOutSideToClose behavior. Please check the JIRA issue for more info.

ROU-4050: Add OnInitialize event and ClickOutsideToClose behavior

---

src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

Remove the existing console log.

ROU-4050_1: Remove Console Log

---

src/scripts/OSFramework/OSUI/Pattern/Accordion/Accordion.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Utils/CreateApiResponse.ts
src/scripts/OutSystems/OSUI/Utils/Menu.ts
src/scripts/OutSystems/OSUI/Utils/Network.ts
src/scripts/OutSystems/OSUI/Utils/Utilities.ts

This PR is for adding consistency at the returning success/error messages to the API methods.

[ROU-4063] - Review error handling on client actions

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/ProgressCircle.ts

This PR is for fixing the vertical order of colors on the Circle gradient.

ROU-4199: fix progressCircle vertical gradient

---

dist/OutSystemsUI.css
src/scripts/OSFramework/OSUI/Pattern/Progress/Bar/scss/_progressbar.scss
src/scss/01-foundations/_root.scss
src/scss/02-layout/_menu-layout-native.scss
src/scss/02-layout/_menu-layout-side.scss
src/scss/02-layout/_menu.scss

This PR is for fixing the z-index on Native Manu and ProgressBar text.

ROU-3417(v2): fixed native menu and progressBar text

---

dist/OutSystemsUI.css
src/scripts/OSFramework/OSUI/Pattern/Rating/scss/_rating.scss

This PR is for merging the fix done on ROU-4210.

ROU-4210-hotfix: merge of fix for rating inside tabs

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Submenu/ISubmenu.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/SubmenuAPI.ts

This PR is for adding a new Submenu API, to disable the click on body interaction.

ROU-4208: add new submenu API

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scss/03-widgets/_table.scss
src/scss/03-widgets/_upload.scss
src/scss/04-patterns/02-content/_chat-message.scss
src/scss/04-patterns/03-interaction/_lightbox-image.scss

This PR is for fixing RTL issues on patterns
- Missing styles for patterns when the RTlL are applied:
- Fix RTL issues on: LightBoxImage, ChatMessage, Tables, popup, Upload
1. Go to each pattern
2. Enable RTL
3. Expected: The RTL is applied correctly on each pattern

ROU-4126: Fix RTL issues

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/DropdownServerSideItem/scss/_dropdownserversideitem.scss
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/AbstractMonthPicker.ts
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/IMonthPicker.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/MonthPickerAPI.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts

This PR is for adding the client action MonthPickerUpdateMonth to update the month on MonthPicker pattern.

ROU-4247: Add feature to update month on MonthPicker

---

src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/scss/_monthpicker.scss
src/scripts/OSFramework/OSUI/Pattern/TimePicker/scss/_timepicker.scss
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/RangeDate/FlatpickrRangeDate.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDate.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts

This PR is for implement a way to force the update bound platform variable when changes at pickers occurs;
Also fix the place where RangeDate was being updating it's local variable as well;

[ROU-4333]: Month and Time Pickers not updating bound variable.

---

pipelines/pr-pipeline.yaml

This PR is for...
-
-
1.
(prefer animated gif)

pipeline module update

---

src/scripts/OSFramework/OSUI/Helper/Dates.ts
src/scripts/OSFramework/OSUI/Pattern/AbstractPattern.ts
src/scripts/OSFramework/OSUI/Pattern/DropdownServerSideItem/scss/_dropdownserversideitem.scss
src/scripts/OSFramework/OSUI/Pattern/Notification/Callbacks.ts
src/scripts/OSFramework/OSUI/Pattern/Notification/Notification.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/Enum.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonthConfig.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/l10ns/A11yContainerInfo.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTimeConfig.ts

This PR is for implement several improvements to:
- Date, Time and Month pickers in terms of accessibility, setting the initial value to the "hidden" input accordingly and updating those values at the OnSelected date/time/moth as well;
- Improved accessibility highlighted state to the DropdownServerSide items;
- Redefined the way onOpen and onClose configs was being set to the Time and Month picker;
- Implemented a validation to ensure OnInitialized callback event is triggered only once at the pattern initialisation;

[ROU-3970]: TimePicker/MonthPicker - Accessibility and other improvements.

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scss/03-widgets/_btn.scss

This PR is for fixing the issue of the text misalignment of the button.
- When a button is are placed inside the footer and enclosed inside a container, they causes a misalignment of the text.
- Changes the selector for btn to be affected only if is a direct child, in order to fix the issue
1. Check each test page
2. The expected are on each test page.

ROU-4378: Button text misalignment when inside footer and on iOS native build

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/AbstractPattern.ts
src/scripts/OSFramework/OSUI/Pattern/AbstractProviderPattern.ts
src/scripts/OSFramework/OSUI/Pattern/InlineSvg/InlineSvg.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/TabsHeaderItem/TabsHeaderItem.ts
src/scss/OutSystemsUI.scss

This PR is for fixing the Submenu and Tabs dispose method when using the back navigation.

ROU-4401: Fixed Submenu and Tabs dispose

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/AbstractPattern.ts
src/scripts/OSFramework/OSUI/Pattern/AbstractProviderPattern.ts
src/scripts/OSFramework/OSUI/Pattern/InlineSvg/InlineSvg.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/TabsHeaderItem/TabsHeaderItem.ts
src/scss/OutSystemsUI.scss

This PR is for merging the hotfix for Submenu and Tabs destroy, fixed on ROU-4401.

Merge ROU-4401

---

.github/workflows/DocsDeployManually.yml
.github/workflows/NPMDeployManually.yml
.github/workflows/release.yml

This PR will add a new workflow in order to deploy documentation manually.

GitHub actions update

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/Providers/OSUI/Carousel/Splide/Splide.ts

This PR is for improving the resize event on the Carousel, as in some cases, like when using the LayoutBaseSection, the Carousel would overflow the screen width

ROU-4422: Improve Carousel resize event

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/RangeSlider/scss/_rangeslider.scss
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/AbstractNoUiSlider.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/NoUiSliderEnum.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/SliderInterval/NoUiSliderIntervalConfig.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/SliderSingle/NoUiSliderSingleConfig.ts

This PR is for adding improvements to A11y, for Range Slider and RangeSliderInterval
- Improved focus styles
- Improved disabled attribute management, so that when disable the screen reader doesn't access the slider.
- Improved A11y warnings related to missing aria-labels

ROU-4366: Sliders A11y Improvements

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Progress/AbstractProgress.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/Bar/ProgressBar.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/ProgressCircle.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/ProgressEnum.ts

This PR is for implement the accessibility improvements identified on team audit for the Progress Bar and Circle.
- Screen reader was not reading the Progress Bar and Circle content
- Replaced the aria-label attribute from Progress Bar and Circle with the aria-labelledby referencing the Content id
1. Go to a page with a Progress Bar or Progress Circle
2. Enable the screen reader
3. Check that the screen reader reads the Progress Bar/Circle percentage, content and the role "progressbar".

ROU-4348: Accessibility improvements identified on team audit for the Progress Bar and Circle

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scss/03-widgets/_upload.scss
src/scss/OutSystemsUI.scss

This PR is for add css for upload widget accessibility
- The upload widget did not have CSS for accessibility implemented
- Added border color for when the Upload widget is focused
- Added border color for when the accessibility features are enabled.
With accessibility features enabled:
With accessibility features disabled:

ROU-4489: Improve Upload Widget focus styles

---

src/scripts/OSFramework/OSUI/Constants.ts
src/scripts/OSFramework/OSUI/Pattern/Notification/Notification.ts

This PR will change the Notification pattern **role** attribute value from **alert** into **alertdialog**.

[ROU-4338] - Notification - Update a11y attribute role value into ariadialog

---

src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts

- This PR is to fix a regression issue on Dropdown Search/Tags where IsDisable is not updated in runtime
- Regression issue on Dropdown Search/Tags where IsDisable is not updated in runtime 
- Introduced in PR for [ROU-4483/ROU-4515](https://github.com/OutSystems/outsystems-ui/pull/803)
- Added back the private method `_manageDisableStatus` to control the disable DOM attribute on the component.
**DropdownTags:**
_Scenario 1_: 
1. Go to `Tests_DropdownTags`.
2. Check that the Dropdown is enabled.
3. Check IsDisabled = True.
4. Click on the 'Apply' button.
5. Check that the Dropdown is disabled.
6. Check IsDisabled = False.
7. Click on the 'Apply' button.
8. Check that the Dropdown is enabled again.
_Scenario 2 - Extensibility_:
1. Go to `Tests_DropdownTags` and directly to the …

ROU-4532: Fix regression on Dropdown Search/Tags changing IsDisable

---

src/scripts/OSFramework/OSUI/Helper/Device.ts
src/scripts/OutSystems/OSUI/Utils/PreviewInDevices/IMessageEventPiD.ts
src/scripts/OutSystems/OSUI/Utils/PreviewInDevices/OnPostMessage.ts

This PR is for improving code readability.

Improve code

---

dist/OutSystemsUI.css
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Event/DOMEvents/Listeners/WindowOnMessage.ts
src/scripts/OSFramework/OSUI/Helper/Device.ts
src/scripts/OutSystems/OSUI/Utils/PreviewInDevices/IMessageEventPiD.ts
src/scripts/OutSystems/OSUI/Utils/PreviewInDevices/OnPostMessage.ts

This PR is for improve visualViewport validation, to prevent returning undefined.

ROU-4536v2: Improve visualViewport validation 

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Constants.ts
src/scripts/OSFramework/OSUI/Helper/ManageAccessibility.ts
src/scripts/OSFramework/OSUI/Pattern/ButtonLoading/ButtonLoading.ts

This PR is for improve Button Loading accessibility
- Replace "atomic" for "aria-atomic" attribute
- Added the "aria-busy" attribute to the button loading

ROU-4518: Accessibility improvements identified on team audit for the Button Loading

---

src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts

This PR is for fixing DatePicker Extensibility's inline config with TodayButton.

ROU-4495: Fixed use case for inline DatePicker

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/l10ns/A11yContainerInfo.ts
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR is for implementing the accessibility improvements for the Datepickers.
- Add an evaluation to only add the aria-describedby attribute when it is a Desktop device since it is not necessary for the mobile.
- Changed the color of the week number in the calendar to fix contrast issues reported by the accessibility checkers.

ROU-4543: Improve accessibility for DatePickers

---

README.md
dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
gulp/ProjectSpecs/DefaultSpecs.js
package.json
src/scripts/OSFramework/OSUI/Constants.ts
src/scss/OutSystemsUI.scss

This PR is for updating version to 2.18.1

Update version to 2.18.1

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts

This PR is for fixing a regression on the DropdownServerSide, by going back to using the onBodyClick.

ROU-4637: Re-added on BodyClick

---

.github/workflows/npm-pre-release.yml
.github/workflows/release.yml
.vscode/settings.json
README.md
dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
gulp/ProjectSpecs/DefaultSpecs.js
package.json
src/scripts/OSFramework/OSUI/Constants.ts
src/scss/OutSystemsUI.scss

- This PR is to update to version 2.18.2
-   [X] requires changes in OutSystems 

Update to version 2.18.2

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Helper/Dates.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDate.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDateConfig.ts

This PR is for fix an issue on datepicker to match values the platform input and Datepicker InitialDate
- The date that are being applied on platform input, doesn't match with datepicker's date and when the date format is different between server and datepicker.
- Created a new method to check the InitialDate that needs to be applied on DatePicker
- Validate in platform input contains value and set as a InitialDate, if the DatePicker doens't have a date defined
1. Open test page
2. Check if the date on input is the same of the platfomr hidden input
3. Open datepicker and select a new date
4. Check again the dates
- …

ROU-4629: Fix an issue on datepicker to match values on InitialDate

---

.eslintignore
.prettierignore
.snyk
.stylelintignore
.vscode/settings.json
README.md
gulp/ProjectSpecs/DefaultSpecs.js
package.json
src/scripts/OSFramework/OSUI/Constants.ts
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

Updated Version 2.18.3 and added .snyk file

Updated Version 2.18.3 and added .snyk file

---

gulp/Tasks/TsTanspile.js
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect.scss

This PR will add:
- Fix a compile issue at development mode;
- Fix a visual issue at DropdownSearch and DropdownTags;

ROU-4642: Dropdown Search/Tags with different behavior between iOS and Android

---

package.json
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is for updating virtual-select version for 1.0.41.

ROU-4523: Updated virtual-select version

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This PR is for fixing the DropdownServerSide when is placed inside the Popup, on certain window sizes.

ROU-4721: fixed dropdown inside popup

---

.github/workflows/ManageDocs.yml
.github/workflows/ManageNPM.yml

This PR will add a validation to ensure deploy documentation and npm-package will occur only if at real repository.

CI Actions: Add validation to ensure it's the real repository.

---

.github/CONTRIBUTING.md
.github/workflows/add-inner-sourcing-label.yaml
.github/workflows/validate-pr-labels.yaml
.github/workflows/validate-pr-title.yaml

- Added first information needed for "Inner Sourcing & Re-Skill | Establish Inner Sourcing Practice".

Added first information for Inner Sourcing

---

src/scss/05-useful/_display.scss

- Requirement for more build-in display options
- Added more display options to scss

Added more display options

---

.vscode/settings.json
src/scripts/Global.d.ts
src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts
src/scripts/OSFramework/OSUI/Pattern/BottomSheet/BottomSheet.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndex/SectionIndex.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/TabsHeaderItem/TabsHeaderItem.ts
src/scripts/OSFramework/OSUI/Pattern/Tooltip/Tooltip.ts

This PR is for applying the prettier configs to the project, so that the PRs are not polluted with the new configs.
* The prettier configs were changed
* This can cause that when a file is changed, the formatting will be changed
* The respective PR of a given task will bring many formatting changed, causing the actual changes to be hidden
* Ran the command: `npm run prettier`
* All changes caused by it, being now commit
1. No actual code change
2. No need to test code

Applying prettier configs to project

---

README.md
package.json
src/scripts/OSFramework/OSUI/Constants.ts
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR is incrementing the version of OSUI.

Version bump 2.18.4

---

gulp/ProjectSpecs/DefaultSpecs.js

This PR will update version into a missing bumped version file.
This file will be responsible to set the version at the compiled files and also at the generated themes for both versions.

Update version at missing file.

---

.github/workflows/AddInnerSourcingLabel.yml
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR is to update GitHub actions for inner sourcing

Update GitHub actions for inner sourcing

---

src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/UpdatePositionOnScroll.ts

This PR is for adding the hotfix for the DatePicker inside the Sidebar into the RC branch.

ROU-4817: Fix pickers inside Sidebar not following scroll

---

src/scripts/OSFramework/OSUI/Feature/Balloon/scss/_balloon.scss

This PR is for fixing the preview of DatePicker inside the OverflowBalloon pattern.

ROU-4863: fix balloon preview

---

.vscode/settings.json
package.json
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is to update the VirtualSelect library to the latest version v1.0.44.
-   [X] requires changes in OutSystems
-   [ ] requires a new sample page in OutSystems (if so, provide a module with changes)

ROU-4875: Update VirtualSelect library to the latest version v1.0.44

---

src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR is for improving the styles of the extensibility flatpickr option of showMonths, allowing for multiple months to appear at the same time. 

ROU-4821: Improve showMonths option support

---

.github/workflows/AddInnerSourcingLabel.yml
.github/workflows/PreRelease.yml
.github/workflows/Release.yml
.github/workflows/ValidatePRLabels.yml
.github/workflows/ValidatePRTitle.yml

This PR will:
- Add new git workflows to the repository
- Updated git-action version to fix node version warning

Repo improvements

---

README.md
gulp/ProjectSpecs/DefaultSpecs.js
package.json
src/scripts/OSFramework/OSUI/Constants.ts
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR is to update the version to 2.19.0
- Updated version to 2.19.0

ROU-0 - Update version to 2.19.0

---

src/scss/03-widgets/_form.scss

This PR will fix an issue at the validation messages in order to fix their position when at IsRTL.
> **Before**:
> <img width="1219" alt="Screenshot 2024-06-07 at 18 13 07" src="https://github.com/OutSystems/outsystems-ui/assets/5339917/68cd931a-c89f-4f94-ab7b-5f0ac20a1af7">
> **After**:
> <img width="1231" alt="Screenshot 2024-06-07 at 18 13 18" src="https://github.com/OutSystems/outsystems-ui/assets/5339917/cd59600d-1246-487e-a449-bc586cf1d150">

ROU-4248: Fix validation messages position

---

package.json
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/NoUiSliderEnum.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/README.md

- Update noUiSlider to latest - v15.8.1
-   [X] requires changes in OutSystems 
-   [ ] requires new sample page in OutSystems

ROU-10821: update noUiSlider to latest - v15.8.1

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This PR is for fixing the DropdownServerSide input position when is inside a Form.

ROU-10848: fixed dropdown inside form

---

src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss

This PR is for fixing the inputs visibility when using the inline extensibility property.

ROU-10935: fix input visibility

---

src/scripts/OSFramework/OSUI/Behaviors/FocusTrap.ts

This PR will revert to the previous behaviour we had at tab navigation at sidebar.

ROU-10963: Revert changes to sidebar

---

.vscode/settings.json
package.json
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is to update the VirtualSelect library to the latest version v1.0.45.
-   [X] requires changes in OutSystems
-   [ ] requires a new sample page in OutSystems (if so, provide a module with changes)

ROU-11057: Update VirtualSelect library to the latest version v1.0.45

---

src/scripts/OSFramework/OSUI/Pattern/DatePicker/AbstractDatePicker.ts
src/scripts/OSFramework/OSUI/Pattern/DatePicker/IDatePicker.ts
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/AbstractMonthPicker.ts
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/IMonthPicker.ts
src/scripts/OSFramework/OSUI/Pattern/TimePicker/AbstractTimePicker.ts
src/scripts/OSFramework/OSUI/Pattern/TimePicker/ITimePicker.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/DatePickerAPI.ts
src/scripts/OutSystems/OSUI/Patterns/MonthPickerAPI.ts
src/scripts/OutSystems/OSUI/Patterns/TimePickerAPI.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts

- It was possible to focus the Input during tabNavigation even when disabled.
- Created a new OnRender API that will check if the input disabled attribute has been updated, if so, tabIndex and aria-hidden attributes of the visible input will be updated accordingly.

ROU-11005: DatePicker, DatePickerRange, MonthPicker and TimePicker

---

src/scss/04-patterns/03-interaction/_input-with-icon.scss

This PR will fix the validation message position once inside an Input With Icon pattern.

ROU-11113: DatePicker and DatePickerRange, Fix validation message position.

---

.vscode/settings.json
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/OutSystems/OSUI/Utils/Menu.ts

This PR is will merge https://github.com/OutSystems/outsystems-ui/pull/986 into dev due to missing signed commits.

ROU-11053: Fixed A11Y issues at the menu when @Mobile and others (#986)

---

src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Utils/Menu.ts
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR will add missing Menu API response to the OnReady and OnDestroy methods.

ROU-11053: Menu - Adding missing API response.

---

src/scripts/OutSystems/OSUI/Utils/Menu.ts

- Fixed validation added on previous PR:

ROU-11183: Fix validation on menu 

---

README.md
gulp/ProjectSpecs/DefaultSpecs.js
package.json
src/scripts/OSFramework/OSUI/Constants.ts
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR is to update version to v2.20.2

ROU-11241: Update version to v2.20.2

---

src/scripts/OSFramework/OSUI/Pattern/Rating/Rating.ts
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR will fix an A11Y issue at Rating pattern.
- Rating placeholders was being cloned and their Ids was being kept the same for each rating element, which causes a bad semantic structure due the usage of duplicated Ids.
- Updated the way elements are being cloned and make sure Id is updated for each element.

ROU-11536: Rating - Fixed A11Y issue at the placeholder elements.

---

src/scripts/OSFramework/OSUI/Feature/Balloon/scss/_balloon.scss
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This PR Will fix an issue at DropdownServerSide.
- Issues at ServiceStudio preview.
- Fixed the css selector that was causing this issues.
- With the Issue:
- With the Fix:

ROU-11563: DropdownServerSide - Fix Studio preview issue.

---

README.md
gulp/ProjectSpecs/DefaultSpecs.js
package.json
src/scripts/OSFramework/OSUI/Constants.ts

- This PR is to increment the dev version to 2.22.1

ROU-11574: Increment dev version to 2.22.1

---

src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR will fix a position issue at the DatePicker.
- Once inside a Popup, calendar was not being properly set with the classes and position issues was happening...
- Removed a duplicated validation that was preventing DatePicker be set with the correct selectors.

ROU-11689: DatePicker - Fixed a DatePiker position issue

---

src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectConfig.ts

- This PR is for fixing a lint issue.

ROU-11742: Fix lint issue

---

.github/os-git-actions/setup-gpg/action.yml
.github/os-git-actions/signed-commit/action.yml
.github/workflows/PreRelease.yml

This PR is for fixing access to the secrets. This PR, undos the changes that were made in the following PR: https://github.com/OutSystems/outsystems-ui/pull/1006

ROU-11492: Fixing access to secrets
