CODEOWNERS
src/scss/04-patterns/06-utilities/_provider-login-button.scss
src/scss/OutSystemsUI.scss

This PR is for adding a new pattern to enable quickly to add login buttons for external providers.

RDUCP-289: adding Provider Login Buttons pattern

---

src/scripts/OSFramework/Event/EventEnum.ts
src/scripts/OSFramework/Event/EventManager.ts
src/scripts/OSFramework/Event/WindowOnMessage.ts
src/scripts/OSFramework/GlobalEnum.ts
src/scripts/OSFramework/Helper/Device.ts
src/scripts/OutSystems/OSUI/Utils/LayoutPrivateOnPostMessage.ts

This PR is for implementing the PostMessage Capability on OutsystemsUI to handle the ODC preview application use case.
- N/A
- Implemented the PostMessage listener to the window;
- Handle the message that comes from the ODC preview to add the styling for the preview devices;
1. Open the app preview;
2. Check if the default device is presenting the content correctly with the notch space;
3. Change the device type;
4. Check that the previewed app notch space is being shown correctly;
(prefer animated gif)

RDUCP 219 - Implement Post Message and Preview styling

---

src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts

This PR is for fixing an issue that was causing the Tabs to trigger layout flickering when setting the first active content on Native Apps, as the code was async and getting too long to finish.

ROU-4073 - Fix issue on android when changing screen

---

src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts

This PR is to fix toggling the disabled attribute on the DatePicker platform input.

ROU-4098: fix DatePicker disabled inputs

---

src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR is for fixing the Tabs indicator, when sued inside the DEPRECATED_Tabs and the orientation vertical.

ROU-4036: fix tabs inside old tabs

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This PR is for fixing DropdownServerSide on Firefox, as this browser doesn't support :has() yet.

ROU-4116: fix dropdownServerSide in firefox

---

src/scripts/OSFramework/Helper/Device.ts
src/scripts/OutSystems/OSUI/Utils/LayoutPrivateOnPostMessage.ts

This PR is for fixing an issue when the NDS preview updates the user agent the information wasn't being correctly updated.
- In the first render of the NDS preview the ios class wasn't applied.
- Add a method to update the user-agent information in the device when it is updated by a post message.
1. Open a mobile app in the NDS preview;
2. The notch style must be applied.
Error
Fix

RDUCP-415: Update the UserAgent information

---

src/scripts/OSFramework/OSUI/Event/BodyOnMouseDown.ts
src/scripts/OSFramework/OSUI/Event/EventEnum.ts
src/scripts/OSFramework/OSUI/Event/EventManager.ts
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

This PR is fix Sidebar closing when selecting text and moving the cursor to the overlay.
- The Sidebar closed when selecting text and moving the cursor to the overlay.
- Added the mousedown event to the body to check if the mouse click started inside the sidebar or not.
- If it started inside the sidebar, it should remain open.
1. Go to a page with a sidebar.
2. Start selecting the text inside the sidebar and move the cursor to the sidebar overlay.
3. The Sidebar should not close.

ROU-4048: Sidebar issue when selecting text and with overlay it closes the sidebar

---

src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/ProgressCircle.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/scss/_progresscircle.scss

This PR is for fixing the ProgressCircle auto size mechanism and overall display properties.
- Now the pattern will look to the lower size (height or width) of the block parent (before was looking at the higher). This would cause the pattern to overflow the parent in some situations.
- Changed block display to inline-block, to correctly align with the expected size of the child and allow other elements to be added at the progressCircle side.
- Improved mechanism to only add observer when needed.
- Improved use-case where the progressCircle is ready at the same time of the parent, making sure that the initial animation is only triggered after the resize is finished.
-   [x] requires changes …

ROU-4057: fix ProgressCircle auto size 

---

src/scripts/OSFramework/OSUI/Pattern/Progress/Bar/scss/_progressbar.scss

This PR is for fixing progressBar progress radius when the Height value is considerable high.

ROU-4119: fix bar border-radius with high heights values

---

src/scripts/OutSystems/OSUI/Utils/NormalizeProviderConfigs.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectConfig.ts

This PR is for implement the missing extensibility configs: allowNewOption, hideClearButton, selectAllOnlyVisible, disabledOptions, minValues
- The for loop in NormalizeProviderConfigs was breaking when an object attribute was not a string.
- Since we are now allowing a new option to be added to the dropdown in runtime, the _checkForFigType() can receive an undefined value.
- Changed the break to continue when the attribute object is not a string in NormalizeProviderConfigs.
- Added a new condition to handle the case os an undefined value in _checkForFigType().
1. Add SetVirtualSelectConfigs to the DropdownSearch and DropdownTags Initialized event 
2. Set the desired configs
3. Check if the Dropdowns are working as expected.
-   [x] clean …

ROU-3862: Extensibility - Missing extensibility features for VirtualSelect

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

This PR is for fix sidebar not closing by clicking on overlay when it starts opened. 
- The MouseDown event handler was being removed instead of added when the sidebar starts open.
1. Go to a page with a sidebar with IsOpen and HasOverlay parameter set to true.
2. Check if it is possible to close the Sidebar by clicking on the overlay.

ROU-4048-2: Fix sidebar not closing when clicking on overlay

---

dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Behaviors/AnimateOnDrag.ts

This PR is for fixing the BottomSheet drag when dragging outside the bounds, the transform was not being reset.
Also simplified code on moveEnd.

ROU-4121: fix BottomSheet drag when outside bounds

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/SectionIndex/ISectionIndex.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndex/SectionIndex.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndexItem/SectionIndexItem.ts

This PR is for improving the SectionIndex behaviour when the class .main-content is not present.

ROU-4084: Improve sectionIndex without main-content

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts

This PR is for fixing an issue related with position of the balloon when Error message appears, since it was not being updated as it can be checked on the image:

[ROU-4115] - DropdownServerSide - Fix position issue when error message appears

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Event/AbstractEventsManager.ts
src/scripts/OutSystems/OSUI/Utils/Menu.ts

This PR is to fix the Menu Drag when on Table landscape (that would be identified as desktop) and when using the option Menu Visible, should not add the drag gestures.
The orientationChange was also fixed, as it was not properly updating the check for gestures. Now this is done using our API.

ROU-4144: fix Menu drag on Tablet landscape

---

src/scripts/OSFramework/Pattern/SectionIndex/scss/_sectionindex.scss
src/scripts/OSFramework/Pattern/Tabs/scss/_tabs.scss
src/scripts/OutSystems/OSUI/Utils/LayoutPrivateBodyCssVars.ts
src/scss/02-layout/_menu.scss

This PR is to bring the code from O11 that consider the status bar in the application UI.
Status bar was not being considered, making the UI overlap the status bar
Bring the commit from O11 that fix the issue
1. Create a new mobile application
2. Add the extensibility configuration to enable the StatusBarOverlaysWebView
3. Generate a mobile app
4. Download the application
5. Open the application on the phone and check if the status bar is being considered (you can also use an emulator for that)
N/A

Rducp 429   status bar

---

src/scripts/OSFramework/Pattern/Tabs/scss/_tabs.scss

This PR is for fixing the preview inside service studio when using tabs
- When using the tabs. Is not possible to drag and drop items inside the tabs if not on the widget tree. The IDE doesn't interpret the display: contents well.
- adds the -servicestudio-display tag to change the display only inside the servicestudio
1. Drag the tabs to a screen
2. Drag a different pattern to the tabs content placeholder. (it can be a simple text, expression or container)

Fix tabs display on servicestudio only

---

gulp/Tasks/ScssTanspile.js
package.json
src/scss/00-abstract/_setup-border-vars.scss
src/scss/01-foundations/_html-elements-img.scss

This PR is for remove duplicated css selectors.
In order to prevent this, also added **postcss-discard-duplicates** that will manage the duplicated css selectors at the compiling moment.

Remove duplicated selectors

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/ErrorCodes.ts
src/scripts/OSFramework/OSUI/Interface/ICallback.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/ISubmenu.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/OSFramework/OSUI/Pattern/Submenu/scss/_submenu.scss
src/scripts/OSFramework/OSUI/Pattern/Tooltip/ITooltip.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/SubmenuAPI.ts

This PR is for fixing a bug on the OpenOnHover, that was not working when using it on the OnReady of a parent block/screen. 
Initialize and OnToggle events were added.
Fixed CSS issue that was causing the submenu to have different when used outside of the Menu, depending if the Layout was SideMneu or TopMenu.

ROU-4123: Submenu fixes and improvements

---

dist/OutSystemsUI.js
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/RangeDate/FlatpickrRangeDate.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDate.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts

This PR is for fix pickers opening via Open Client Action when disabled.
- When the input is disabled, the Pickers can still be opened by using the Open API Client Actions, and the patterns works and changes dates after that.
- Add validation to check if the input is disabled before run the provider's open, clear and update methods.
1. Go to a test page with a DatePicker
2. Disable the DatePicker input
3. Run the pattern's Open, Clear and Update Client Actions.

ROU-4140: Flatpickr Patterns issue when input is disabled

---

dist/OutSystemsUI.js
src/scripts/OutSystems/OSUI/Utils/NormalizeProviderConfigs.ts

This PR is to fix the method AbstractNormalizeProviderConfigs for the scenario where we are dealing with the type HTMLElement. If so then get the element from the DOM, using the elementId passed and by having keyValue.toLowerCase().trim() first was causing errors while trying to run this operation.
-  By having keyValue.toLowerCase().trim() first was causing errors while trying to get the Element from the DOM, using the elementId passed.
- Changed the order of the validations to check first for the HTML Element.
1. Go to the Date Picker and Date Range functional test screens.
2. In the extensibility configurations set the attribute positionElement = "b3-b59-b14-Content".
3. Click apply (where we're calling SetFlatpickrConfigs client action).
4. Opened the Date Picker.
5. Checked that it …

Fixed AbstractNormalizeProviderConfigs

---

src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDate.ts

This PR is for fixing an issue related with the redraw that happen when he **UpdateInitialDate** API method is triggered, since the **onDateSelectedEvent** method will not be fired at the redraw, the **_isUpdatedInitialDateByClientAction** property will not be updated.

[ROU-4158] - Fix an issue related with the UpdateInitialDate API method.

---

src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR is for fix input inside tabs issue and accessibility issues:
- Fix the tabs changing when using arrow keys in tabs content
- Add behavior that moves focus to the first tab, when arrow right is pressed when the focus is on the last tab
- Add behavior that moves focus to the last tab, when arrow left is pressed when the focus is on the first tab
- The tabs changed when using the arrow keys to move the cursor position of an input inside the tab content. 
- Change `_handleKeypressEvent` to validate if the key press event targetElement is the active header tab.
- If true, then change tabs.
- If false, then do nothing.
- Change `_handleKeypressEvent` to change to the first tab if last the active header tab and the right key was pressed.
- Change `_handleKeypressEvent` to change to the …

ROU-4198: Input inside tabs issue

---

src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR is for fix tabs display on servicestudio only.
- It was not possible to drag and drop content to the tabs placeholder in service studio preview.
- Cherry picking from ODC branch:
- Adds the -servicestudio-display tag to change the display only inside the servicestudio.
1. Go to Service Studio
2. Drag a button to the Tabs' content placeholder
Expected: The button appears in Tabs' content

ROU-4142: Fix tabs display on servicestudio only

---

dist/OutSystemsUI.css
src/scripts/OSFramework/OSUI/Pattern/Rating/scss/_rating.scss

This PR is for fixing an issue on chromium browsers when using the Rating inside the new tabs pattern.

ROU-4210: fixed rating inside tabs

---

dist/OutSystemsUI.css
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR is for increase the area of dropping elements on tabs content. Please check the JIRA issue for more information
- Now the area to drag and drop elements is to short;
- The area of dropping elements on content tabs was increase only when is empty;
Previous:
After:

ROU-4212: Increase area of dropping elements on tabs

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR is for allow firing the List OnScrollEnding inside Tabs.
- With the oveflow-y: auto on tabs content item, doesn't allow the OnScrollEnding event to be fired.
- Created a CSS variable to handle the tabs content overflow based on definition of height parameter;
- Updated the CSS rule of overflow on tabs content item, to have the new css variable ('--tabs-content-item-overflow');
- On the method setHeight, a validation was created to set the correct overflow based on height;

ROU-4217: Allow firing the List OnScrollEnding inside Tabs

---

gulp/templates/PatternFramework_HasProvider/Provider/Provider.ts
gulp/templates/PatternFramework_HasProvider/Provider_HasMode/Provider.ts
src/scripts/OSFramework/GlobalEnum.ts
src/scripts/OSFramework/Pattern/AbstractProviderPattern.ts
src/scripts/Providers/Carousel/Splide/Splide.ts
src/scripts/Providers/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/Datepicker/Flatpickr/RangeDate/FlatpickrRangeDate.ts
src/scripts/Providers/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
src/scripts/Providers/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/RangeSlider/NoUISlider/AbstractNoUiSlider.ts
src/scripts/Providers/Timepicker/Flatpickr/FlatpickrTime.ts

This PR is for adding the provider configs event. This event will be triggered after the setProviderConfigs methods are invoked and the new configs applied.
- The lack of this event, caused somethings for a flickering to occur, since the pattern is first built, and then destroyed once the method setProviderConfigs is invoked.
- The previously abstract method `registerCallback` in the class `AbstractProviderPattern` was not implemented.
- This method encapsulates the logic of the events `Initialized` (previously dispersed through out the code) and the newly created event `OnProviderConfigsApplied`.
- Two new methods were added in the class `AbstractProviderPattern`:
- triggerPlatformEventInitialized: will raise the `Initialized` event of the pattern;
- triggerPlatformEventplatformCallback: …

RDUCP-472: Adding Provider Configs apply event

---

src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Pattern/AbstractProviderPattern.ts
src/scripts/Providers/OSUI/Carousel/Splide/Splide.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/AbstractNoUiSlider.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts

This PR is for adding the provider configs event. This event will be triggered after the setProviderConfigs methods are invoked and the new configs applied.
- The lack of this event, caused somethings for a flickering to occur, since the pattern is first built, and then destroyed once the method setProviderConfigs is invoked.
- The previously abstract method `registerCallback` in the class `AbstractProviderPattern` was not implemented.
- This method encapsulates the logic of the events `Initialized` (previously dispersed through out the code) and the newly created event `OnProviderConfigsApplied`.
- Two new methods were added in the class `AbstractProviderPattern`:
- triggerPlatformEventInitialized: will raise the `Initialized` event of the pattern;
- triggerPlatformEventplatformCallback: …

RDUCP-472o11: Adding Provider Configs apply event

---

dist/OutSystemsUI.css
src/scss/03-widgets/_form.scss

This PR is for fixing the alignment of error messages in some use cases. Please check the JIRA issue for more information.
- Error labels are wrongly positioned on some inputs:
- Review the CSS rules of all use cases of validation messages and fix the issue, by default:
1. Open the test page
2. Click on Save button
3. Expected: all the inputs on page will received the error messages and will be placed in the right positions.

ROU-4154: Fix the alignment of error messages

---

dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

This PR is for fixing the issue of closing the sidebar when an element clicked is at body level.
- When a sidebar is used with elements that is detach (Dropdowns Tags and Search) from block and moved to body level, the Sidebar closes always when a selection is made on dropdowns options:
- Created a validation on method "_overlayMouseDownCallback" that will validate if the element clicked ids the same as the overlay:
1. Open Sample page
2. Click on button to open the Sidebar
3. Select each dropdown
4. Select any option / multiple options on dropdown
5. Expected: The Sidebar will keep open on each interaction
-   [ ] …

ROU-4223: Prevent Sidebar closes when a detached element is clicked

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Event/AbstractEventsManager.ts
src/scripts/OSFramework/OSUI/Event/BodyOnClick.ts
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts

This PR is for adding feature to detached patterns to prevent trigger the body click global event:
- Rollback the previous fix to prevent sidebar close when has detached patterns inside
- Add methods **enableBodyClickEvent** & **disableBodyClickEvent** to prevent body click triggering on patterns that are detached from the block and uses the global body click event
- Add a getter **getBodyClickStatus** to check the global body click event status
- Review the global event **BodyOnClick** to add the status validation of body click and trigger it only if is enabled
-   [ ] requires new sample page in OutSystems (if …

ROU-4223: Add feature to detached patterns to prevent trigger the body click global event

---

dist/OutSystemsUI.css
src/scss/02-layout/_header-layout-side.scss

This PR is for fixing an issue on layout native when the menu behavior is expandable.
- The CSS rules are incorrectly applied:
- Removed the CSS that are causing the issue:
1. Open Sample Page
2. Check if the layout are correct
3. Enable the RTL
4. Expected: The layout will change the view based on RTL and the menu icon are visible

ROU-3789: Fix desktop issue on LayoutNative expandable

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/Tooltip/Tooltip.ts

This PR is for change the target element of moved ballon from out of context of the pattern. The Tooltip and the DropdownServerSide were affected with this change.

ROU-4203: Change the moved elements to active screen

---

src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR is for fixing a glitch in DatePickerRange where the gray part was still shown when both start- and enddate were on the same date.
[Sample page](https://dekkinga.outsystemscloud.com/OutsystemsUITests/Screen1)
- The gray part was still shown on the left side of the selected date range when both start- and enddate were on the same date
- Added a rule to the SCSS code to separate the date ranges where both the startRange and endRange classes were on the same day from the existing date ranges where both classes are on different days.
1. Open a DateRangePicker
2. Select the same day twice to get a range of 1 day.
3. Open the DateRangePicker again.
4. The gray part on the left should be gone after the fix is implemented.
Before the fix:
After the fix:
-   [ ] …

Fixed a glitch in DatePickerRange

---

dist/OutSystemsUI.css
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

This PR is for fixing when a Popup is opened, when a Sidebar is already open. This would result on clicking the Popup would close the Sidebar also.

ROU-4259: fix popup with sidebar

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Helper/Dates.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickrConfig.ts

This PR is for fixing am issue that was causing the Today Button to trigger a null Date, when the MaxDate was set to 'today'.
This was happening because inside Service Studio, the parameters are DateTime type, and when used to set Date types, the Date would come with a fixed hour ,even if not used, which could make the validations comparisons on the provider to fail, as it could happen that the Date on the Today Button would have a later hour, or even just minutes.
- Added a new private method to check if TimeFormat is disabled. If it is, then we set the MaxDate to 23:59:59 hour and the MinDate to 0:0:0:0 hour.
- …

ROU-4245: Fix MaxDate validation when using DateTime

---

dist/OutSystemsUI.css
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR is to rollback a fix for the Tabs, as it caused some impact on other patterns and its own behaviour.

ROU-4280:  rollback fix

---

dist/OutSystemsUI.css
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss
src/scripts/OSFramework/OSUI/Pattern/TabsContentItem/TabsContentItem.ts

This PR is for fixing the Tabs when there's a repaint caused by changes outside of the Tabs.
To fix this, the CSS snap property is added always when the focus is not inside the tabs, to make sure, the Snap takes care of correctly adapting the items size. 
With this change, the target of the accessibility attributes was changed to the selfElement of each Content Item, instead of the parent OS block. This not only prevents the the arrow key navigation when the focus inside the Tabs, but also fixes the Accessibility behaviour, that [according to guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/) should have a visible tabindex=0 element, before entering on the content inside:
Some validations were also improved on the observers callback, to prevent console …

ROU-4280: Fix tabs render and observer errors

---

dist/OutSystemsUI.css
src/scss/01-foundations/_resets.scss

This PR is for fixing the positioning of datepicker native icon on chrome

ROU-4263: Fix issue on input date icon positioning

---

dist/OutSystemsUI.css
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR is for fixing the positioning of datpicker ballon whe used insed a LayoutSide with thr RTL enabled.
- Open the Sample page
- Enable the RTL on switch element
- Open each picker
Expected: The ballon of each picker will open above the sidemenu

ROU-4225: Fix positioning layer systems for datepicker

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/DatePicker/AbstractDatePicker.ts
src/scripts/OSFramework/OSUI/Pattern/DatePicker/IDatePicker.ts
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/AbstractMonthPicker.ts
src/scripts/OSFramework/OSUI/Pattern/TimePicker/AbstractTimePicker.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/DatePickerAPI.ts
src/scripts/OutSystems/OSUI/Patterns/MonthPickerAPI.ts
src/scripts/OutSystems/OSUI/Patterns/TimePickerAPI.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts

This PR is for adding a client action for each picker to update the prompt message.

ROU-4307: Add client action to all pickers to update prompt message

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/ErrorCodes.ts
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Helper/SVG.ts
src/scripts/OSFramework/OSUI/Pattern/InlineSvg/Callbacks.ts
src/scripts/OSFramework/OSUI/Pattern/InlineSvg/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/InlineSvg/IInlineSvg.ts
src/scripts/OSFramework/OSUI/Pattern/InlineSvg/InlineSvg.ts
src/scripts/OSFramework/OSUI/Pattern/InlineSvg/InlineSvgConfig.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/InlineSvgAPI.ts

This PR is for implement the new InlineSVG
- Created the OSFramework.OSUI.Patterns.InlineSvg.InlineSvg
- Now the Initialized event should be triggered after component's build.
- Now the SVGCode in validated before assign it to the config.
- Created the OSFramework.OSUI.Patterns.InlineSvg.InlineSvgConfig
- Created the OSFramework.OSUI.Helper.SVG that contains the isValid method to validate the SVGCode.
- Created the OutSystems.OSUI.Patterns.InlineSvgAPI
- Added the necessary interfaces and errorCodes.

ROU-3349: InlineSVG - Implement with the new architecture

---

src/scripts/OSFramework/OSUI/Pattern/AbstractPattern.ts
src/scripts/OSFramework/OSUI/Pattern/AbstractProviderPattern.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/DropdownServerSideItem/DropdownServerSideItem.ts
src/scripts/Providers/OSUI/Carousel/Splide/Splide.ts
src/scripts/Providers/OSUI/Carousel/Splide/SplideConfig.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickrConfig.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/RangeDate/FlatpickrRangeDate.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/RangeDate/FlatpickrRangeDateConfig.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDate.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDateConfig.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectConfig.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Search/VirtualSelectSearch.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Search/VirtualSelectSearchConfig.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Tags/VirtualSelectTags.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Tags/VirtualSelectTagsConfig.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonth.ts
src/scripts/Providers/OSUI/Monthpicker/Flatpickr/FlatpickrMonthConfig.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/AbstractNoUiSliderConfig.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/SliderInterval/NoUiSliderIntervalConfig.ts
src/scripts/Providers/OSUI/RangeSlider/NoUISlider/SliderSingle/NoUiSliderSingleConfig.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts
src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTimeConfig.ts

This PR is for add code consistency and also fix some issues related with the previous ROU-3565 PRs versions.
- **Improvements**:
- > Removed underscore to all Protected members.
- **Fixed Issues**:
- > Avoid DropdownServerSide toggleEvent be trigger twice.
- > Initialized Event of DropdownServerSideItem is now being fired.

[ROU-3656 V3] - Add Initialized event to all new components - P2

---

src/scripts/OutSystems/OSUI/Patterns/TabsContentItemAPI.ts
src/scripts/OutSystems/OSUI/Patterns/TabsHeaderItemAPI.ts

This PR is for fixing an issue at TabsContentItem and TabsHeaderItem that was preventing to set the Initialized callback event.

[ROU-3656-v4]: Add Initialized event to all new components - P2

---

src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/scss/_monthpicker.scss
src/scripts/OSFramework/OSUI/Pattern/TimePicker/scss/_timepicker.scss

This PR is for replace Pickers selector into first-of-type due to a use case where input losses this selector.
At form validation, this "hidden" inputs will loose this selector (flatpickr-input), and at that moment they will be visible, so, this approach must be kept.

[ROU-4333]: Replace changed CSS

---

src/scripts/OSFramework/OSUI/Event/DOMEvents/Listeners/AbstractListener.ts
src/scripts/OSFramework/OSUI/Event/DOMEvents/Listeners/BodyOnScroll.ts

This PR will fix an issue related with the OnBodyScroll. 
Since the event is being set to the body element and in some cases the scroll is being set to other elements, such as ".active-screen" container, once scroll occurs inside this last one, the event was not being triggered at the body since body has an overflow hidden.
In order to grant all the use cases, **useCapture** property has been added in order to proper manage this event property accordingly.

Fixed issue that was preventing OnBodyScroll event to be triggered.

---

src/scripts/OSFramework/OSUI/Behaviors/FocusTrap.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/Notification/Notification.ts
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

This PR will fix the issues:
-  I took the opportunity to add some consistency to the **FocusTrap** implementation across patterns that are using it;
- Also fix an issue at **DropdownServerSide** that was preventing on having accessible styles, since it’s being added at the active-screen container where the selector responsible for adding the accessible styles (has-accessible-features) to the patterns is not present, since it’s being added to the layout.
- Fixed an issue at **FocusTrap** feature that was preventing focus navigation in the correct order. Took the opportunity to add also other improvements to it, for example, triggering the callbacks, since when defined the focus behaviour should be tackled at the pattern side, and not at the FocusTrap feature, otherwise we are setting …

[ROU-4349]: Focus Trap doesn't work well on Firefox and Safari

---

dist/OutSystemsUI.css
src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/scss/_progresscircle.scss

This PR is for fixing a breaking-change on the SVGInline when used inside the ProgressCircle, due to the CSS Class change on the SVG Pattern.

ROU-4390: Fix InlineSVG inside progress-circle

---

src/scripts/OSFramework/OSUI/Pattern/InlineSvg/InlineSvg.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts

This PR is for fixing an issue that was preventing Dropdown to work when data was completed loaded and Dropdown was opened.

[ROU-4360] - Dropdown Search/Tags doesn't close when is open before data is loaded

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
package.json
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectConfig.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/VirtualSelect.d.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is to update Virtual Select v1.0.39 and add the ability to allow a normalized search (ignoring diacritics).
- Now, Dropdown Search and Dropdown Tags will be using the latest version of their library provider (VirtualSelect v1.0.39).
This version also brings new extensibility configurations that were added to the VirtualSelectConfigs structure that contains the properties available on the SetVirtualSelectConfigs client action - _ariaLabelText, emptyValue, search, searchFormLabel, searchGroup, searchNormalize, showDropboxAsPopup, textDirection_.
- Now, Dropdown Search and Dropdown Tags components will allow a normalized search (ignoring diacritics).
**Test Case 1 - Regression and Normalized Search:**
1. Go to ests_DropdownSearch
2. Run regression tests
3. Search by `Gonc` and check …

ROU-4355 Update Virtual Select v1.0.39

---

dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts
src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/OverflowMenu.ts

This PR is for fixing the OverflowMenu dispose when the pattern is destroyed, without first never being opened, and so the Balloon feature never creates the FloatingPosition util instance
1. Go to OverflowMenu Screen
2. Navigate to another screen
3. Use back navigation
Expected: No errors triggered

Fix OverflowMenu feature dispose

---

dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

This PR is for fixing the closing of a nested Sidebar, when pressing Esc, that was closing all Sidebars at once.

Fix sidebar on keypress

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Video/Video.ts
src/scripts/OSFramework/OSUI/Pattern/Video/VideoConfig.ts

This PR is to change the parameter name from Subtitles to Captions and review the method to set tracks.
- Change variables names with subtitle prefix to captions
- Change the configs parameters from Subtitles to Captions

ROU-4250: Change name from Subtitles to Captions

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts
src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/OverflowMenuConfig.ts
src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/scss/_overflowmenu.scss

This PR is for adding the following fixes to the OverflowMenu:
- Fix shape rounded style in mobile;
- Fix hover style when shape is not Sharp and a link is the first child inside the Balloon.
- Fixed Esc behaviour inside Sidebar. Now when pressing Esc, the Sidebar is not closed, only the OverflowMenu.
- Added missing configs validations.

ROU-4405: Minor fixes on OverflowMenu 

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Video/IVideo.ts
src/scripts/OSFramework/OSUI/Pattern/Video/Video.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/VideoAPI.ts

This PR is for adding the new client actions for video:
- VideoGetState: Returns the reproduction state of the video.
- VideoPause: Pause a Video with a given identifier.
- VideoPlay:Play a Video with a given identifier.
- Now it's possible to Play and Pause a video using actions and based on conditions
- Create client actions: **VideoGetState** (Returns the reproduction state of the video), **VideoPause** (Pause a Video with a given identifier) and **VideoPlay** (Play a Video with a given identifier)
1. Open the sample page
2. Click on Play Video and / or Pause Video
3. Expected: The video will react to each client action
-   [ ] requires changes in OutSystems (if so, provide a module with …

ROU-3280: Add client actions for Video

---

dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/AnimatedLabel.ts

This PR is for improving the typification on AnimatedLabel's _inputStateToggle method, done on the external PR #764 

ROU-4392: Improve AnimatedLabel typification

---

dist/OutSystemsUI.css
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
src/scripts/OSFramework/OSUI/Pattern/DropdownServerSideItem/scss/_dropdownserversideitem.scss

This PR is for improving DropdownDownServerSide event management, for two main reasons:
- Fix Phone behaviour, where it wasn't possible to close the Dropdown by clicking on the overlay, through the bodyClick.
- Improve overall performance, as the events were never removed when the Dropdown was closed, which meant, for example, that for every click on the screen it would call the bodyClick callback, for each Dropdown on the screen.

ROU-4412: Improve DropdownDownServerSide event management

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Event/DOMEvents/AbstractEvent.ts
src/scripts/OSFramework/OSUI/Event/DOMEvents/AbstractEventsManager.ts
src/scripts/OSFramework/OSUI/Event/DOMEvents/IEvent.ts

This PR is for improving the management of the events. This was found when improving the lifecycle of the orientationChange event (OutSystems code), that was not being added again in runtime, as the _events map wasn't correctly removing the eventType, when the last handler was removed.

ROU-4327: Improve event management on remove handler

---

dist/OutSystemsUI.css
src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/scss/_animated-label.scss

This PR is for fixing the issue on AnimatedLabels when is used inside lists.
- The AnimatedLabel uses negative margins to place the text and this goes to outside the pattern and when is used inside elements with overflow: hidden, this issue will occur:
- Created a selector that push down the animated label when is the first child of a list:
1. Open Test page
2. Check if the AnimatedLabels is correctly displayed;

ROU-4420: Fix an issue on AnimatedLabel inside lists

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Tabs/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR is for improving the way we manage the size of the Tabs Indicator element. 
Due to recurrent issues related to browser/system zoom, now the indicator size is defined using width/height (based on Tabs orientation) from the current TabsHeaderItem. Before this was using transform: scale(), to allow a transition on size, without affecting performance.

ROU-4231: Improve Indicator size management

---

dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Notification/Notification.ts

This PR is for fixing the closing of the tooltip, when used inside a Notification (with InteractToClose as true). 
The stopPropagation() was preventing the tooltip callback to close it, to get triggered, when the Notification closes, leaving the tooltip still open on the screen

ROU-4446: Fix tooltip inside notification

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Video/IVideo.ts
src/scripts/OSFramework/OSUI/Pattern/Video/Video.ts
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/VideoAPI.ts

This PR is for adding the new feature to Video to jump to a specific time of a video.
- A new client action called VideoJumpToTime was added to give the ability to jump to a specific time of a given video.
**Test Case 1**
1. Go to Sample Page
2. Click on Jump To Time Video Button
3. Expected: The video will change the seconds to 6 and the Infor box will have "Code = 200 ; Message = Success; VideoJumpToTime value is equal to VideoCurrentTime: True; CurrentTime: 6"
**Test Case 2**
1. Go to Sample Page
2. Click on Jump To Time Video - Error Button
3. Expected: The video action error will be triggered
-   [ ] requires …

ROU-4410: Add public method VideoJumpToTime

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Helper/Times.ts
src/scripts/OSFramework/OSUI/Pattern/Video/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/Video/IVideo.ts
src/scripts/OSFramework/OSUI/Pattern/Video/Video.ts
src/scripts/OutSystems/OSUI/Patterns/VideoAPI.ts

This PR is for changing the behavior of applying time in VideoJumpToTime. Now the the time is defined as time and we convert the value into seconds to apply on video.
- Now the the time is defined as time and we convert the value into seconds to apply on video.

Video: Change the time type to be applied on VideoJumpTime

---

src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/scss/_monthpicker.scss
src/scripts/OSFramework/OSUI/Pattern/TimePicker/scss/_timepicker.scss

This PR is to fix the Service Studio preview of input on time-related pickers
- The platform input was not visible in design time.
- Added a CSS _-servicestudio-_ rule to make it visible in the Service Studio
1. Open the module containing all pickers.
2. Check that the input is now visible in the Design time
3. Open the page in runtime and check that everything is working as before
- Before:
- After the fix:

ROU-4482: Fixed SS preview of input on time-related pickers

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Progress/AbstractProgress.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/Bar/ProgressBar.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/ProgressCircle.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/ProgressEnum.ts

This PR is for add aria-label to the ProgressBar/Circle when empty content
- Accessibility checkers were indicating an issue when the element referenced in aria-labelledby attribute is not readable.
- When the content placeholder contains any element, we replace the aria-label attribute from Progress Bar and Circle with the aria-labelledby referencing the Content id, otherwise, we keep the aria-label attribute.
- If the content inside the Content placeholders is not readable, it is the responsibility of the user to make it accessible.
1. Go to a page with a Progress Bar or Progress Circle
2. Enable the screen reader
3. Check that the screen reader reads the Progress Bar/Circle percentage, content, and the role "progressbar".
-   [x] clean …

ROU-4348: Add aria-label to the ProgressBar/Circle when empty content

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Behaviors/FocusManager.ts
src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts
src/scripts/OSFramework/OSUI/Pattern/BottomSheet/BottomSheet.ts
src/scripts/OSFramework/OSUI/Pattern/Notification/Notification.ts
src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

This PR is for create the abstraction to focus on the trigger when we close a component (sidebar, notification, balloon and bottom sheet) 
- When we close the notification, stay focused on the notification element. The element is hidden but the screen reader keeps focused on the element.
- When the sidebar is closed, it does not return focus to the previous focusable element
- When a component starts opening, the focus was set to the body when closed.
- Created the FocusManager class to be instantiated in overlay components to manage the focus when closing the component.
- The FocusManager.storeLastFocusedElement stores the element activeElement reference
- The FocusManager.returnFocusToElement return the focus to the stored element. If the element does not exist on the page, is not …

ROU-4462: Abstraction to focus on the trigger when we close a component (sidebar, notification, etc) 

---

src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickrConfig.ts

This PR is for fix an issue at DatePicker when Initial and Min date were the same that was blocking the ability on selecting the MinDate.

[ROU-4493]: DatePicker - Fixed issue when InitialDate = MinDate

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
package.json
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is to update Virtual Select v1.0.40.
- Now, Dropdown Search and Dropdown Tags will be using the latest version of their library provider (VirtualSelect v1.0.40).
**Test Case 1 - Regression:**
1. Go to Tests_DropdownSearch
2. Run regression tests
4. Repeated the same tests on Tests_DropdownTags 
**Test Case 1 - Focus Issue with Starting Values:**
1. Go to Test_StartingValues_DropdownSearch
2. Check that the screen stays on the top and not focus on the bottom Dropdown
4. Repeated the same tests with a Test_StartingValues_DropdownTags 
-   [X] requires changes in OutSystems

Update Virtual Select v1.0.40

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/Tabs/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss
src/scss/OutSystemsUI.scss

This PR is for reverting the previous PR for this ROU, as it was adding some layout shifting in some scenarios.
Now, instead of a CSS solution, we validating the existence of an active dropdown on the active content item, and prevent the OnChange in case there's one (making it mandatory for the dropdown to be closed first). 
This solution was implemented instead of the CSS one with :has(), due to lack of Firefox support.

ROU-4510: Added alternate fix for the Tabs fix

---

dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Pattern/BottomSheet/BottomSheet.ts

This PR is for adding accessibility improvements to the BottomSheet
- Correct role is now applied
- Home/End keys support was added

ROU-4504: add BottomSheet a11y improvements

---

dist/OutSystemsUI.css
src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/scss/_monthpicker.scss
src/scripts/OSFramework/OSUI/Pattern/TimePicker/scss/_timepicker.scss

This PR is for fixing an issue on Datepicker that show the hidden datepicker input.
- The Datepicker are showing the hidden input
- Change the selectors on CSS to hide the input
1. Open test page
2. Check the Pickers input
3. Expected: no duplicated input are shown

ROU-4540: Fix issue on Datepicker that show the hidden datepicker input

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OutSystems/OSUI/Utils/LayoutPrivateSkipContentLink.ts

This PR is for adding an API to set the link on SkipContent to fix the warnings on A11Y checkers
- Created an API to set the link on skip content element
1. Open test page
2. Run an A11Y checker
3. Expected: No warnings related to skip content link

ROU-4529: Improve accessibility on the SkipContent link

---

dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts
src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/OverflowMenu.ts

This PR is for prevent scroll when using arrow up and down keys on OverflowMenu
- When using the arrow up and down keys to open the OverflowMenu and navigate between the items, the page scroll up and down.
- Added the event.preventDefault() to the keydown event handlers of Balloon and OverflowMenu.

ROU-4537: Prevent scroll when using arrow up and down keys on OverflowMenu

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts

This PR is for fix the Overflow Menu not opening correctly inside Tabs.
- When opening the Overflow Menu inside tab, the content of the previous Tab was appearing.
- Changed the focus to be done async using OSUI.Helper.AsyncInvocation()
Before:
After:

ROU-4537: Fix Overflow Menu issue inside Tabs

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Pattern/Rating/Rating.ts
src/scripts/OSFramework/OSUI/Pattern/Rating/scss/_rating.scss

This PR is for improve rating component in terms of accessibility.
- add logic to manage aria-hidden and area checked;
- remove the logic that was adding wcaghideText to the first input label;
- improve scss file;
- add styles to prevent half from being visible when is not half rating;
- add styles to guarantee the empty editable rating is visible;
1. Open the test page
2. Run an A11Y checker
3. Run the page using a screen reader
4. Expected: No warnings related to rating
(prefer animated gif)

ROU-4527 - [OSUI] - Accessibility improvements identified on team audit for the Rating

---

src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR is for adding Accessibility improvements on the DatePickers. 
This PR must be tested together with the changes made on the Flatpickr fork: https://github.com/OutSystems/flatpickr/pull/7 
- Added keydown support for Today Button
- Changed place where Today Button was appended, due to new focus trap spans added on Flatpickr PR
- Added styles for accessibility focus 

ROU-4495: Added Accessibility improvements

---

src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/scss/_overflowmenu.scss

This PR is for fixing the css for OverflowMenu's article element, that had display: block, preventing other elements to be placed on its side.

ROU-4559: Fix overflowMenu display property

---

dist/OutSystemsUI.css
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Feature/Balloon/scss/_balloon.scss

This PR is for fixing the OverflowMenu position, when affected by overflow: hidden from parent elements.

ROU-4574: Fix OverflowMenu position

---

dist/OutSystemsUI.css
src/scss/02-layout/_menu.scss

This PR fixes a Header preview issue, when using the LayoutBase block on the Service Studio.
This PR code is based on the external PR: https://github.com/OutSystems/outsystems-ui/pull/832. 
Thank you @df-gss for the contribution!

ROU-4563: Fix Header Preview on LayoutBase

---

src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR is for fix the issue happens when a date gets selected and Time is focused which if calendar time is not inside browser boundaries a scroll will occurs to all content and it's not possible to revert it.

[ROU-4542]: DatePicker - Fix screen scroll when time is in use.

---

src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts

This PR is for changing the bodyOnClick on the Balloon feature, to validate if the e.target is present inside the OverflowMenu pattern.

ROU-4593: Fixed Balloon onBodyClick

---

src/scripts/OSFramework/OSUI/Constants.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/Tooltip/Tooltip.ts

This PR is for removing a use-case on ODC, when closing the Tooltip or DropdownServerSide by clicking on a button or link.
- Removed global onBody click for these patterns.
- Add onBlur event when needed, to cover the same use-cases as the bodyOnClick did. This will make it work for O11 and ODC.

ROU-4598: Fixed onBlur behaviour on ODC and streamlined overall code

---

src/scripts/OutSystems/OSUI/Utils/Utilities.ts

This PR is for fixing the favicon API on PWA applications
- The API AddFavicon was not working on PWA since the selector that checks if the favicon exists was editing `link rel="apple-touch-icon" ` instead of creating the link for the favicon.
- change Favicon selector to be more strict.
1. Generate a PWA Application that has a favicon
2. Check if the favicon is there when running the layout

ROU-4633 - [OSUI] - Issue applying favicon icon in PWA application

---

src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/scss/_monthpicker.scss
src/scripts/OSFramework/OSUI/Pattern/TimePicker/scss/_timepicker.scss

This PR is for fixing an issue related with the visibility of the hidden input of the DatePicker, MonthPicker and TimePicker.
- When the hidden input changed to the invalid state via validation of form widget. The input was shown due to internal react logic. 
- Change the selector on flatpickr components to guarantee that the internal input doesn't appear after a form widget validation change it to invalid.
1. Add a mandatory picker to a form widget.
2. Add a Button to submit the form.
3. Run the screen, leave the input empty and submit the form
4. Check if the picker remains with **only** 1 input after changed to invalid
Repeat the test for datePicker, timePicker and monthPicker
-   [ ] …

ROU-4635 - [OSUI] - Datepicker validation showing hidden input

---

src/scripts/OSFramework/OSUI/Pattern/TimePicker/scss/_timepicker.scss

This PR is for...
- fix time-picker selector to be stronger than .chrome input[type=time].

- fix time-picker selector to be stronger than .chrome input[type=time].

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OutSystems/OSUI/Utils/DeviceDetection.ts

This PR is to fix the SetDeviceBreakpoint assigning a desktop as a tablet.
-  When at desktop and if widowHeight <= tabletMax it will be set the tablet class, which is wrong.
- Simplified the logic so it can work as expected:
- The user sets the phoneWidth and tabletWidth breakpoints.
- If both window dimensions are smaller than the phoneWidth, then it is a phone.
- If both window dimensions are bigger than the phoneWidth and smaller than the tabletWidth, then it is a tablet.
- If both window dimensions are bigger than the tabletWidth, then it is a desktop.
- To achieve that, we just need to validate the biggest dimension:
- If landscape, we check the width
- If portrait, we check the height. 
- So these changes were done:
- Created a new variable, windowSize, to get the largest size …

ROU-4582:  SetBreakPoints - Remove wrong tablet validation when window height > width 

---

dist/OutSystemsUI.css
dist/OutSystemsUI.js
src/scripts/OutSystems/OSUI/Utils/DeviceDetection.ts

This PR is to change the SetDeviceBreakpoints behavior
- Now, the SetDeviceBreakpoints will just consider the windowWidth when setting the device.
1. Go to a page using the SetDeviceBreakpoints
2. Check that the device accordingly when modifying the windowWidth

ROU-4582: SetBreakPoints - Remove wrong tablet validation when window height > width 

---

dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/Constants.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts

This PR is for fixing the Tab focusing on the input of the previous Tab when using TabKey to navigate.
- When setting the tabIndex of the focusable elements inside the inactive and active Tabs, some inputs such as datetime, date and time were not being reached.
- Because of that, when using the tab key to navigate from the Tab Header to the Tab Content, the input of the previous Tab Content was being focused.
- Edited the string used to get all the focusable elements in OSFramework.Helper.Dom.GetFocusableElements
1. Go to a page with inputs of the type date, datetime, and time inside Tabs.
2. For all the Tabs, check that it is not possible to reach the previous Tab's content using the Tab key.
-   [x] clean all warnings and errors of …

ROU-4647: Tabs - TabIndex leave current tabs

---

src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Helper/FocusFirstInvalidInput.ts

This PR is for fixing the issue on FocusFirstInvalidInput action.
- After a validation in a form an call the action FocusFirstInvalidInput to validate if exists any invalid inputs, the action never focus on the first invalid input:
- The action was reviewed on typescript to make it assync from the validation of the form. This is needed because we need to wait for platform to apply the non-valid classes
- Added the **scrollend** event listener to the scrollable element when the parameter IsSmooth is true, to focus only when the scroll animation is ended.
1. Open sample page
2. Scroll to the button on bottom
3. Click on each button
4. Expected: The page will scroll up and the first invalid input will be focused
-   [X] clean all warnings …

ROU-4654: FocusFirstInvalidInput not focusing

---

dist/OutSystemsUI.css
dist/OutSystemsUI.d.ts
dist/OutSystemsUI.js
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Helper/Dom.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSideEnum.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This issue happens only in ODC, as the new version of react-dom adds all events on the ReactContainer, instead of adding it on every widget. This causes an issue with widgets inside the DropdownServerSide, when placed inside the Popup. As the Popup is placed outside the reactContainer, together with the MoveElement we are doing on the Dropdown, it causes all widgets inside to loose the attached listeners. 
- Added method to check if an element is inside the Popup widget.
- Added exception to only use MoveElement on DropdownServerSide if its not inside Popup, otherwise add custom class
- Added different CSS with that class, to adjust behaviour for dropdown inside the Popup
This approach was followed, as no other tested solved the issue. Removing the MoveElement and changing the overall …

ROU-4664: Prevent dom move when inside popup

---

src/scripts/Providers/OSUI/RangeSlider/NoUISlider/Utils.ts

This PR is for fix an issue when an extensibility attribute is missing at RangeSlider by adding an extra validation before checking it's value.

ROU-4645: Add a missing validation when range was not defined.

---

gulp/ProjectSpecs/DefaultSpecs.js
gulp/ProjectSpecs/ScssStructure/PatternsUtilities.js
gulp/Tasks/CreateScssFile.js
gulp/Tasks/ScssTanspile.js
gulp/Tasks/TsTanspile.js
gulpfile.js
src/scripts/OSFramework/OSUI/Event/DOMEvents/Listeners/ScreenOnScroll.ts
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/Enum.ts
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/UpdatePositionOnScroll.ts

- This PR will fix the issue that was happening when a scroll starts at a Picker input.
- It will also fix an issue that was preventing scrollEvent to be assigned to the container that has the scroll behaviour when app is native or pwa;

[ROU-3816]: Pickers in mobile are not closing on a scroll inside the input

---

src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts

This PR will fix an issue at Tabs component. It has an unexpected behaviour when PageDown or PageUp are pressed if the target are elements inside tabsContent.

[ROU-4699]: Fixed an issue when PageDown or PageUp keys are pressed.

---

src/scripts/OSFramework/OSUI/Event/DOMEvents/Listeners/AbstractListener.ts
src/scripts/OSFramework/OSUI/Event/DOMEvents/Listeners/ScreenOnScroll.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/RangeDate/FlatpickrRangeDate.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDate.ts
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/UpdatePositionOnScroll.ts

**This PR will add fixes related with:**
> ToggleNativebehaviour API:
- Method was implemented in both DatePicker and DatePickerRange, which ends into an issue since the redraw was happening in both contexts when at DatePickerRange this will never happen.
> ScreenOnScroll event:
- Implemented logic to validate if ScreenOnScroll container has changed, if so, update the targetElement accordingly, this will happen at the screen transition when the container with scroll will be the same but not the same instance!
Also improved code readability on contexts mentioned above.

[ROU-3816 V2]: Fixed ScreenOnScroll and ToggleNativeBehavior API issues

---

src/scripts/OSFramework/OSUI/Pattern/SectionIndex/SectionIndex.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndexItem/SectionIndexItem.ts

This PR is for fixing the keyboard tab navigation between the SectionIndexItem patterns.

ROU-4672: Fix keyboard tab navigation

---

src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR is for improving the A11y styles on MonthPicker, when using the keyboard.

ROU-3947: Improve A11y styles on MonthPicker

---

src/scripts/OSFramework/OSUI/Event/DOMEvents/Listeners/ScreenOnScroll.ts

This PR is will add the missing validation use case when ScrollEvent is being added to the proper container.

[ROU-3816]: Missing validation when adding ScrollEvent

---

src/scripts/OSFramework/OSUI/Pattern/Tooltip/scss/_tooltip.scss

This PR is for fixing UI consistency of Tooltip word breaking, when it has a long text inside and/or link elements.

ROU-4719: Fixed Tooltip word breaking

---

src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts

This PR is for fixing the sidebar toggle when the ClickOutsideToClose feature was on.
- We discovered that the body handlers that should be removed on close were not.
- remove bind(this) from add Handler on openSidebar;
1. Config a sample with a sidebar, on the onInitialized call the API to Config the ClickOutsudeToClose feature
2. Add Buttons on the screen to open and toggle the sidebar
3. Add a button on the sidebar to close itself
4. Run the page and check if the toggle interaction work properly
5. Check if the handlers are not being duplicated under OSFramework.OSUI.Event.DOMEvents.Listeners.GlobalListenerManager.Instance;
-   [ ] requires changes in OutSystems (if so, provide a module …

ROU-4692 - [OSUI] Sidebar is not working as expected when a button is used to open

---

src/scripts/OSFramework/OSUI/Pattern/AccordionItem/AccordionItem.ts
src/scripts/OSFramework/OSUI/Pattern/AccordionItem/AccordionItemConfig.ts
src/scripts/OSFramework/OSUI/Pattern/AccordionItem/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/AccordionItem/scss/_accordion-item.scss

[Sample page](https://personal-hgmyk7op.outsystemscloud.com/CustomOSComponents/Accordion)
- To toggle the accordion item content you can click anywhere on the title
- I added a new option to the accordion item that will allow the developers to choose the icon to be responsible on the accordion toggle instead of the complete title
1.  I added a new property to the accordion item **ToggleWithIcon** and initialized it with _false_ and a new style class **PatternToggleWithIcon**
2.  Inside the accordion I added a new variable that will store the property
3. I updated the __addEvents()_ method to check for the new property and if it true, we will add the event listener to the icon. If not, add the event to the title.
4. The same for __removeEvent()_
5. I added the new class to the block when …

Add a new feature to accordion item component

---

src/scripts/OSFramework/OSUI/Helper/Device.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectConfig.ts

This PR is for fixing an issue on mobile devices that trigger the onresise event and closes unexpectedly the keyboard.
- When a DropdownSearch is opened on an tablet android device, the keyboard opens and closes unexpectedly because of the OnResize event that is triggered
- Create a method IsMobileDevice that returns if is a mobile device
- Added an validation that uses the value of IsMobileDevice to add the event OnOrientationChange for mobile devices or the OnResize event to desktop applications
1. Open sample page on an Android Device in landscape
2. Open a dropdown
3. Click on the input search to open keyboard (Expected: the keyboard will continue open)
4. Rotate device (Expected: The keyboard and dropdown will close)
5. Open a dropdown
6. Click on the input search to open keyboard …

ROU-4712: Dropdown Search closes unexpectedly when is used on an Android Tablet

---

gulp/ProjectSpecs/ScssStructure/Widgets.js
gulp/Tasks/CreateScss/GetPartialsList.js
gulp/Tasks/CreateScss/SectionIndex.js
src/scss/03-widgets/_popover-odc.scss
src/scss/03-widgets/_popover.scss
src/scss/ODC.OutSystemsUI.scss

This PR is for fixing the Popover widget position when is used with RTL enabled
- Due to the new improvements made on Popover widget calculations on platform side, the CSS created form Popover under the OutSystems UI, apply the wrong position of widget.
- Remove css for popover widget related to position
1. Open Sample Page
2. Enable the RTL
3. Select the Widgets on Category Patterns dropdown
4. Scroll down the page and Open the Popover
Expected: The Popover will open and will be placed properly

ROU-4771: Remove css for popover widget related to position

---

src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/UpdatePositionOnScroll.ts

This PR is for ~adjusting the scroll behavior so that the time picker, behaves like the other pickers.~ improving the comments and the code.
- When scrolling from the input that associated with the time picker, the time picker would not close (unlike the other pickers);
- The reason was, that the time picker has an input that gets focused, once it's open. This made the activeElement to be different from the element where the picker was instantiate;
- ~Added a private attribute, `_isTimePicker`, to the class `UpdatePositionOnScroll`~
- ~On the callback of the scroll, now checking for that attribute, in case it's true (meaning it the timepicker, the code will not check if the scroll starting element is the same as where the picker is instantiated.~
- The behavior for the timepicker was …

ROU-4723: closing timePicker on scroll

---

src/scss/04-patterns/03-interaction/_floating-actions.scss

This PR is for fixing a layer system issue due the place css variable was defined, which ends on non z-index definition for this pattern.
> Before the fix:
> After the fix:
Thank you for the awareness @os-raquel.

[ROU-4794]: FloatingActions - Fix layer systems issue.

---

src/scripts/OSFramework/OSUI/Pattern/Rating/IRating.ts
src/scripts/OSFramework/OSUI/Pattern/Rating/Rating.ts
src/scripts/OSFramework/OSUI/Pattern/Rating/scss/_rating.scss
src/scripts/OutSystems/OSUI/ErrorCodes.ts
src/scripts/OutSystems/OSUI/Patterns/RatingAPI.ts

This PR is for adding new Disable/Enable API methods to the Rating.
It will also change the **IsEdit** behaviour since now IsEdit will only be used to set the rating as in edit/reading mode.
Previous IsEdit was being manage disable status, which ends into an a11y issue once when **IsEdit=False** user was not able to focus the rating neither through keyboard navigation or mouse click.
> Before new API methods and IsEdit changed behaviour:
> After changes made:

[ROU-4795]: Rating - Add Disable/Enable API methods.

---

src/scripts/OSFramework/OSUI/Pattern/Rating/scss/_rating.scss

This PR will add disabled style to the rating pattern.
> If a11y features disabled:
> If a11y features enabled:

[ROU-4795]: Rating - Added rating disabled style.

---

src/scss/10-deprecated/_horizontal-scroll-deprecated.scss

This PR will fix an issue that was preventing table to fit 100% into the container width.
> Before the fix:
> After the fix:

[ROU-4800]: ScrollableArea - Fix issue that was preventing table gets full width.

---

src/scss/07-keyframes/_animate.scss

This PR is for fixing the scss compilation for the scaleup animation.
The issue with the screen-transition scss compilation (transition with multiple properties resulta in 3 transition properties being compiled). From my research and attempts, this seems an issue from scss and was not able to find any workaround. That being said, in runtime it will still work as expected.

ROU-4807: fix transform property

---

src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/UpdatePositionOnScroll.ts

This PR is for fixing the pickers inside the Sidebar not following scroll.
- When inside a Sidebar, the calendar position was not updated when scrolling.
- Added a scroll event listener to the Sidebar element that updates the calendar position on scroll.

ROU-4817: Fix pickers inside Sidebar not following scroll

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

This PR is for removing the fallbacks for the :has() CSS selector on Firefox, as its fully supported since version 121: https://web.dev/blog/web-platform-12-2023?hl=en#the_has_selector

ROU-4704: Removed :has() exceptions

---

src/scripts/OSFramework/OSUI/Helper/Dates.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickrConfig.ts

This PR is to improve the Datepicker render when MinDate, MaxDate and InitialDate have the same value;
- When the MinDate, MaxDate, and InitialDate had the same value, the DatePicker was not rendering with a value on initialised.
- Guarantee that minDate is set with time 00:00:00 and maxDate with time 23:59:59 when the widget is config with TimeFormat disabled.
1. Fill MinDate, MaxDate and InitialDate with the same date (2024-04-18)
2. Choose disabled on TimeFormat;
3. Click Apply and check if the date picker renders with an initial value;
-   [ ] requires new sample page in OutSystems (if so, provide a module with …

ROU-4868: [OSUI] Datepicker doesn't show Initial Date, when MinDate is equal to MaxDate.

---

src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts

This PR is for fixing an issue related with the status of the ballon
- When the ballon was open and its state change via back button, the body click listener was still active, but the ballon reference was lost since it was dispose.
- remove listeners on ballon dispose;
1. Go to page 
2. Navigate via link to the same page
3. Open Ballon
4. Click back button to the same page
5. Click somewhere on the page
6. Check that there aren't errors on the console

ROU-4881 - [OSUI] - Issue with overflow menu triggers console error

---

src/scripts/OutSystems/OSUI/Patterns/DropdownAPI.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts

This PR is to add `SilentOnChangedEvent` to the _DropdownClear_ API.
- DropdownClear client action was triggering the on-change event and causing an infinite loop:
- Added to the _DropdownClear_ API a new input parameter called `SilentOnChangedEvent` to control when to trigger the on-change event.
1. Go to the test page
2. Select some options on the left Dropdown
3. Checked the change is triggered and the feedback message is displayed
4. Select some options on the right Dropdown
5. Checked the change is not triggered and no feedback message is displayed
6. Repeated the same steps for dropdown tags
-   [X] requires changes in OutSystems
-   [ ] requires new sample page in OutSystems (if so, …

ROU-4865: Add SilentOnChangedEvent to DropdownClear API

---

src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDate.ts

This PR is for fixing an issue related to the clear API. It was only working on the second call.
- When the date picker was configured using only one var for the initial date and the selected date, the clear action didn't work. This was happening because we were doing a redraw when was not needed
- improve change property validation for the initial date;
1. Go to the section **Reuse InitialDate as SelectedDate** on the sample page
2. Click on the clear button
3. Check the input is clear and the date inside the DatePicker is unselected
-   [ ] requires new sample page in OutSystems (if so, provide a module with …

ROU-4898 - Issue with date pickers in OutSystems UI v2.18.4

---

src/scripts/OSFramework/OSUI/Behaviors/Scroll.ts
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Helper/Dom.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndex/ISectionIndex.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndex/SectionIndex.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndex/scss/_sectionindex.scss
src/scripts/OSFramework/OSUI/Pattern/SectionIndexItem/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndexItem/ISectionIndexItem.ts
src/scripts/OSFramework/OSUI/Pattern/SectionIndexItem/SectionIndexItem.ts

This PR is for improving the way the SectionIndex deals with the scroll, in particular the smooth option.
- The overall calculations were simplified, and now the offset targets the value of the SectionIndex topPosition.
- The Scroll behaviour was changed to use the [ScrollIntoView api](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).
- As this api does not have a offset option, this is now achieved with CSS, using the [scroll-margin property](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin).
- A new helper was created on Dom, to return the value of a CSS Custom Property. 
- …

ROU-4890: improve SectionIndex scroll behavior

---

src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/AnimatedLabel.ts

This PR is for fixing an issue on animated labels when the input is of type number.
- When we were using an Animated Label with an input of type number, and we start typing some integers and then add a '+', '-' or 'e' and the label will drop overlapping the input.
- Improve empty input validation on AnimatedLabel component;
1. Go to Animated Label on “With input type - Number” section. Check if the label is correct  when you fill the input with "e" and click outside (blur)
2. Go to Animated Label on “With input type - Number” section. Check if the label is correct  when you fill the input with "E" and click outside (blur)
3. Go to Animated Label on “With input type - Number” section. Check if the label is correct  when you fill the input with "123-" and click outside (blur)
4. Go to …

ROU-4903: [OSUI] - AnimatedLabel issue with symbols on Integer Input

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR is for fixing Dropdown Server Side issues after integrating the OSUI Balloon
- Inside new Tabs and on some Tab contents and not in RTL the right border is not displayed: 
- Inside new Tabs when the dropdown is open and we click on another Tab without closing the dropdown balloon, we temporarily see the balloon flickering on the left side of the screen: 
- In the Dropdown Server Side, subtracted the size of its border from the width so it is displayed correctly inside the Tabs.
- In the Tabs, added "opacity:0" to the not active tabs content items.
-   [ ] requires new sample page in OutSystems (if so, …

ROU-4770: Fix Dropdown Server Side issues after integrating the OSUI Balloon

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss
src/scripts/OSFramework/OSUI/Pattern/Tooltip/Tooltip.ts

This PR is for fixing:
- Dropdown inside Tabs, only in windows
- Revert tabs code as it was causing issues with drag experience
- Fix tooltip closing when clicking on another tooltip

ROU-4738-v2: fix drop and tooltip issues

---

src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR will fix an issue that was preventing tabsContent to be visible at design time (inside ServiceStudio).

ROU-10751: TabsContent is not visible at DesignTime

---

src/scripts/OSFramework/OSUI/Pattern/AccordionItem/AccordionItem.ts
src/scripts/OSFramework/OSUI/Pattern/AccordionItem/AccordionItemConfig.ts
src/scripts/OSFramework/OSUI/Pattern/AccordionItem/Enum.ts
src/scripts/OSFramework/OSUI/Pattern/AccordionItem/scss/_accordion-item.scss
src/scripts/OutSystems/OSUI/Patterns/AccordionItemAPI.ts

This PR is inspired by the [PR](https://github.com/OutSystems/outsystems-ui/pull/890) made by [@ElevenMou](https://github.com/ElevenMou) and introduces the ability to change the clickable area that will trigger the opening/closing of the Accordion Item.
- There was no easy ability to make just the icon of the accordion clickable.
- Added the required functionality via API:
```
OutSystems.OSUI.Patterns.AccordionItemAPI.ToggleClickableZone("ACCORDIONITEMID", true);
```
1. Go to test page, the active clickable area via the buttons
2. Depending of the value, the clickable area should be the title or just the icon.
- …

ROU-4717: Adding ability to change the clicking area

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This PR will:
- Fix a style issue that was preventing DropdownServerSide to be set with no-valid (error) style;
> Before:
> After:
- Enhance A11Y outline style to the DropdownServerSide options ballon when it's focused;
> Before:
> After:

ROU10687: DropdownServerSide style issues

---

typedoc.json

This PR is to update typedoc.json to fix the error after updating type docs
- While running `npx typedoc` we were getting the following issue right after updating **typedoc** to **v0.25.13** and **typedoc-umlclass** to **v0.9.0**
`[error] Tried to set an option (umlClassDiagram) that was not declared. You may have meant:
media
customCss
htmlLang
emit
name
readme
cname
gaID
sort
Error: Process completed with exit code 1.
`
- Added a new setting to `typedoc.json` according to the example from [typedoc-umlclass](https://www.npmjs.com/package/typedoc-umlclass):
`"plugin": [
"typedoc-umlclass"
]`
1. Ran  `npx typedoc` 
2. Check that the error doesn't occur now
-   [ ] requires …

ROU-0 Update typedoc.json to fix error

---

package.json

This PR is rollback TypeScript version back to 4.5.0

ROU-0: rollback TypeScript version back to 4.5.0

---

package.json

This PR is to rollback some dependencies since the docs generation started to fail: 
- rollback TypeScript version back to `v4.5.0`
- rollback typedoc version back to:
```
"typedoc": "^0.23.9",
"typedoc-plugin-merge-modules": "^4.0.1",
"typedoc-umlclass": "^0.7.0",
```

ROU-0: rollback TypeScript and type doc versions

---

src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts

This PR is for fixing the Dropdown Server Side for Androdid
- Dropdown Server Side was closing everytime on Android phones due to keyboard opening.
- Make sure the onResize event is only applied when we are not on phone;
1. Go to sample
2. Try to interact with the widget on an Android device

ROU-10860 - [OSUI] - Dropdown Server Side not working for Android

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR is for fixing the the arrow keypress on DropdownServerSide, to correctly focus on first item and prevent scroll when doing that.

ROU-10843: fix dropdownServerSide arrow interaction

---

src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/AnimatedLabel.ts

This PR is for fixing the issue that prevents the AnimatedLabel to correctly appear as active on the screen load, when there's already a default value.
This was happening as the build method was async, while the render method responsible for the active state was running first than the build. As such, the render method was also made async.

ROU-10851: fix AnimatedLabel on init value

---

src/scripts/Providers/OSUI/RangeSlider/NoUISlider/Utils.ts

This PR is for adding a range property validation before trying to manipulate it.
- In O11 this was never an issue, because empty structures objects always return an empty object range: {}.
- In ODC, this correctly returns nothing from the Platform, so we need to make sure the range exists, before doing anything with it.

ROU-10852: add range validation

---

src/scripts/OSFramework/OSUI/Pattern/Tooltip/Tooltip.ts

This PR is for fixing the tooltip's parameter StartsOpen, as it got broken after the Balloon feature implementation.
Now, when the StartsOpen is true, the Balloon open method is called on build().

ROU-10909: fix tooltip StartsOpen

---

src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts

This PR is for fixing the toggle of the DisableTabItem API, to re-add display: contents instead of display: block.

ROU-10913: add display contents on enable item

---

.editorconfig
src/scripts/OSFramework/OSUI/Helper/URL.ts
src/scripts/OSFramework/OSUI/Pattern/Video/Video.ts

This PR is for fixing an issue that caused the Video component not to play as expected.
- This occurred when using a URL from a resource within the app since the URL gets appended with a session hash, which prevented the video extension from being properly calculated.
- Created a method to properly calculate the file extension for a given URL despite the fact of having a session hash or not.
1. Create a sample screen with an instance of video using a URL from a resource (e.g. `Resources.osuivideo_mp4.URL`) 
2. Check that the video works
3. Added an instance of video using a URL from an external source (e.g. `http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4`)
4. Check that the video works
-   [ ] clean all …

ROU-10919: Fixed how to get URL file extension for video component

---

src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickrConfig.ts

- Issue where the "Today's" button in the DatePicker/DatePickerRange components did not have a `tabindex = -1` when the DatePicker was closed.
- This occurred when the ShowTodayButton option was set to True and the DatePicker/DatePickerRange instance was closed.
- Changed the OnClose handler to set properly `tabindex = -1` when closing the DatePicker/DatePickerRange.
- Added a new OnOpen handler to set properly `tabindex = 0` when opening the DatePicker/DatePickerRange.
- Changed `addTodayBtn()` to set `tabindex = -1` when opened and `tabindex = 0` when closed.
1. Go to the DatePicker sample screen
2. Enable ShowTodayButton
3. Clicked on Apply 
4. Open the DatePicker 
5. Check the today button works and has `tabindex = 0`
6. Close the Date Picker
7.  Check the Today button has `tabindex = …

ROU-10923: DatePicker TodayButton didn't have tabindex=-1 when closed

---

src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

- Issue causing misalignment in the DatePicker/DatePickerRange components when used inline:
- Changed the CSS selector to cover the **inline** scenario
-**Test 1:**
- Open the "Tests_DatePicker" test page for the date picker
- Set params in the "SetProviderConfigs" block with  "inline" = "true"
- Click  on the button with the text "Apply Provider Configs"
- Check the calendar is now inline and visible 
- Switches "ParameterChange (Enable Today button)" to True
- Check the Today’s button appears
- Repeated the same test at "Tests_DatePickerRange"
-**Test 2 - Regression:**
- Review test from where the issue was added `ROU-4542`
- Open Sample screen
- Set the browser window size as 1200x680
- Click ApplyBtn
- Set time as enabled
- Click on DatePicker input
- Select a Date on the DatePicker
- …

ROU-10927: Fixed DatePicker/Range inline having position-fixed rule breaking the UI expected when inline

---

src/scripts/OutSystems/OSUI/Utils/Menu.ts

This PR is for fixing an issue that prevented MenuIcon from receiving the focus and triggering the associated action when navigating with the keyboard.
- This issue occurred when using the Tab key to reach the MenuIcon on phone or tablet-sized displays, and pressing Enter or Space did not activate the Menu Icon as expected.
- Fixed the way the keyCodes were being (incorrectly) validated as strings instead of numbers. 
1. Go to a sample screen with Menu Icon
2. Resize the screen to tablet or mobile display
3. Tab to the menu icon
4. Press enter and space key
5. Check that the menu opens
- After the fix:
-   [ ] requires changes in OutSystems
-   [ ] requires new sample page in OutSystems

ROU-11016: Fix SetMenuIconListeners

---

src/scss/03-widgets/_button-group.scss
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR is for fixing the position of the ButtonGroup's validation message.
Before:
After:

ROU-11042: fix button-group validation message

---

src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss

- Hidden input (added through OutSystems platform) was being visible when DatePicker or DatePickerRange was used inside an InputWithIcon pattern.
- Updated the selector in order to remove the context to get that first input.
> Before the fix
> ![Screenshot 2024-08-29 at 14 26 08](https://github.com/user-attachments/assets/16c5583b-69c9-41d4-b68b-d90c58f5bc36)
> After the fix
> ![Screenshot 2024-08-29 at 14 26 19](https://github.com/user-attachments/assets/ccdc7fce-67cb-48b4-876f-7120f7a5551f)

ROU-11113: DatePicker - Fix DatePicker and DatePickerRange hidden input visibility

---

.vscode/settings.json
src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
src/scripts/OutSystems/OSUI/Utils/Menu.ts

This PR will fix several issues at the menu, mostly A11Y related...
- Keyboard navigation issues after a resize into mobile devices resolutions and Menu be as a mobile menu (sidebar menu);
- Submenu once inside a menu is being trap the user during keyboard navigation;
- MenuShow and MenuHide APIs not working;
Keyboard navigation issues after a resize into mobile devices resolutions and Menu be as a mobile menu:
- User was getting keyboard navigation issues due the missing of update a11y attributes and events;
- User was able to navigate through the elements but without being trapped at the menu context, again, due to the missing update of the a11y attributes;
Submenu once inside a menu is being trap the user during keyboard navigation:
- Once the keyboard navigation was in use and a …

ROU-11053: Fixed A11Y issues at the menu when @Mobile and others

---

src/scripts/OSFramework/OSUI/Pattern/BottomSheet/scss/_bottomsheet.scss
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSideEnum.ts
src/scss/04-patterns/03-interaction/_floating-actions.scss

This PR will fix some issues at DropdownServerSide, FloatingActions and BottomSheet patterns...
> **DropdownServerSide**
>> If Search Input gets typed text and an icon to clear the input is visible, once the clear input icon gets clicked it will close the Dropdown. This occurs only at phone devices.
> **FloatingActions**
>> CSS selector issue that was preventing intend animation occurs.
> **BottomSheet**
>> CSS invalid property usage.
> **DropdownServerSide**
>> Once the click occurs logic was added to prevent the close.
> **FloatingActions**
>> Fixed CSS selector.
> **BottomSheet**
>> Fixed CSS selector.
Note:
This PR will also fix https://github.com/OutSystems/outsystems-ui/issues/989, and https://github.com/OutSystems/outsystems-ui/issues/990

ROU-11189: DropdownServerSide, FloatingActions and BottomSheet

---

src/scripts/OSFramework/OSUI/Helper/Device.ts
src/scripts/OutSystems/OSUI/Utils/Menu.ts
src/scripts/osui.ts

- The app templates were released with some javascript nodes calling OutSystems UI framework APIs that the Developer doesn't know and that were only present in tablets and for older apps there's some manual work to be done.
- Since we now have `MenuReady` and `MenuDestroy` client actions, we should enclose this logic to avoid having JS nodes spread over the templates.
- Included the Orientation Change logic on Menu `OnReady` (this method now receives a callback) and `OnDestroy`
- Deprecated `AddMenuOnOrientationChange` and `RemoveMenuOnOrientationChange`
- Fixed some typos on the `Menu.ts` file
- Added the comments and `@deprecate` symbol to all methods within `osui.ts` file and added a new namespace to fallback the deprecated methods
- Fixed an issue raised by Snyk on the function …

ROU-11183: Include OnOrientationChange logic on MenuReady/MenuDestroy

---

src/scripts/OSFramework/OSUI/Helper/Dates.ts
src/scripts/Providers/OSUI/Datepicker/Flatpickr/SingleDate/FlatpickrSingleDate.ts

This PR will fix an issue related with certain time zones.
- When used at Pacific time zone (for example) dates do not map to the given ones.
- This was related with the format of the given platform string date, containing "-" as separator instead of "/", new Date() JS function was returning a wrong date because of that.

ROU-11179: DatePicker - Fix an issue when used at certain time zones

---

src/scripts/OutSystems/OSUI/Utils/Accessibility.ts

This PR is for fixing an accessibility issue on the skipToContent link.
- A tabIndex= "0" was added to the main content but removed, and that should only happen after the focus changes to another element.
- remove tabIndex on a target blur listener;
- add blur function to remove tab index and listener;
1. Reach skip to content link using TAB navigation and trigger it
2. Check the main-content element on the dom has tabindex=”0”
3. Use tab or mouse to navigate to other element
4. Check the main-content element on the dom doesn’t have tabindex anymore
5. Check the blur listeners of main-content element, it should have been removed
-   [ ] requires changes in OutSystems (if so, provide a module …

ROU-11287: [OSUI] - Defect with Skip to Content link

---

src/scss/03-widgets/_radio-button.scss
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR will fix a styling issue at RadioButton widget.
- When HighContrast mod was on and HasAccessibility features layout attribute was set to True, RadioButton styling was not being set as it should.
- Only happening at Windows.
- Redefined the css selector into a specific selector instead of the usage of a shorthand one.

[ROU-11342]: RadioButton - Fixed styling issue when HighContrast mode is on.

---

src/scripts/OSFramework/OSUI/Pattern/Progress/Bar/scss/_progressbar.scss
src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/scss/_progresscircle.scss
src/scripts/OSFramework/OSUI/Pattern/Progress/ProgressEnum.ts

This PR is for adding new css variables to enable the developer to override the speed animation of the Progress Bar + Circle.
- When the speed of updating the value of the progress was higher than 5 per second, the progress was stuck in 0%, until the end, or until the update speed slowed down.
- Added 2 new css variables that will enable the developer to override the animation speed value, making it fluid
- `--progress-initial-speed`
- `--progress-speed`  
```
.override-speed .osui-progress-bar {
--progress-initial-speed: 0.1s;
}
```
-   [ ] requires new sample page in OutSystems (if so, provide a module with …

ROU-11384: Adding new css variables to control progress animation speed

---

src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect.scss
src/scss/00-abstract/_mixins.scss
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

This PR is for...
[Sample page](https://outsystemsui-dev.outsystemsenterprise.com/AT_OSUIFunctional_ROU11403/Tests_DropdownSearch)
Accessibility styling was not being applied to Virtual Select's Dropbox since it is not present inside of the layout element, which in turn holds the accessibility class.
- The accessibility class has been added to the dropbox if also present on the layout
- Focus styling changed from the toggle-all-button to the toggle-all-checkbox
- Fixed Dropbox options' focus outline
1.
(prefer animated gif)

ROU-11403: Enabling accessibility styling for Virtual Select

---

.github/os-git-actions/setup-gpg/action.yml
.github/os-git-actions/signed-commit/action.yml
.github/workflows/PreRelease.yml

This PR is for adding small improvements on the github actions.
- The way the github actions were accessing to the secrets and passing as input parameter to other actions;
- The version of the external github action `actions/checkout`
- Now, github actions that require secrets access to them directly
- `actions/checkout` was standardized to v4
- Tested changes in the sandbox

ROU-11456: Small improvements in pipelines

---

README.md
gulp/ProjectSpecs/DefaultSpecs.js
package.json
src/scripts/OSFramework/OSUI/Constants.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is to update the VirtualSelect library to the latest version **v1.0.47**
- Updated Virtual Select provider to **v1.0.47**
- Incremented OutSystems UI version to **v2.22.0**

ROU-11479: Update Virtual Select provider to v1.0.47

---

src/scripts/OutSystems/OSUI/Utils/Menu.ts

This PR is for fixing a bug on the Menu utils client action ("SetActiveMenuItems").
- The code was prepared to select the active item based on its index inside the parent, however since we implemented the focus trap, the submenu has more children that are not submenu items. 
- Because of this I changed the selector to be stronger than just the child index.   
- Get Active SubItem using a strong selector pointing to the specific sub-items instead of the children list;
1. Go to sample
2. On Page Ready fill the input with an index that exists inside the submenu
-   [ ] requires new sample page in OutSystems (if so, …

ROU-11521: the behavior of "ActiveSubMenu" differs in the OutSystems UI different versions

---

src/scripts/OSFramework/OSUI/Constants.ts
src/scripts/OSFramework/OSUI/Helper/Device.ts
src/scripts/OutSystems/OSUI/Utils/LayoutPrivate.ts
src/scss/01-foundations/_resets.scss

This PR will fix an issue when: 
- The user is using a device with an Arabic Language
and
- The application **IS NOT** being set with Arabic Language
- It makes date type inputs to loose the date format and show the date in the wrong format,
- Added a body class selector and force the text direction to RTL to all type of date and datetime inputs at the screen.

ROU-11464: Input type Date and DateTime - Fix a date format issues.

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSideEnum.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss

This PR will fix a position issue to the DropdownServerSide when used inside a BottomSheet pattern.
- Due to fixed position when BottomSheet also have a position fixed defined.
- DropdownServerSide will now be able to understand if it's inside a BottomSheet pattern;
- If so, options balloon container will be moved to the content container context;
- Added a new style class to be possible to style the position accordingly;
- Added new styles to proper place the balloon when under this context;
With the Issue:
With the Fix:

ROU-11549: DropdownServerSide - Fix a position issue when inside BottomSheet.

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSideEnum.ts

This PR will add the ability to DropdownServerSide options balloon container be also moved to outside of it's context when inside Notification and/or SideBar Patterns.
- Position issues, when inside Notification and/or SideBar patterns.
- Added extra validation to move balloon options to outside of pattern context.

ROU-11549: DrodownServerSide - Fixed missing validation to also move balloon options.

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss

This PR Will fix a layer position issues when inside ServiceStudio.
- When inside certain type of elements due to position absolute under the context of the parent element, DropdownServerSideOptions was being shown behind another elements.
- Changed from `position: absolute` into `position: relative` when inside Studio.

ROU-11563: DropdownServerSide - Fix layer position issues at studio.

---

src/scss/03-widgets/_inputs-and-textareas.scss

- On a Screen with an Input or Textarea widget, it was not possible to select the text using the pointer when the `Enabled` property is `False`, ie, they are disabled.
- Removed the `pointer-events: none` in the selector `.form-control[data-input][disabled], .form-control[data-textarea][disabled]`
1. Go to a Screen with an Input or Textarea widget.
2. Set their Enabled property to False.
3. Check that now it is possible to select the text inside the Input/Textarea in runtime.

ROU-11631: Input and Textarea do not allow the text to be selected when the component is disabled 

---

src/scss/03-widgets/_inputs-and-textareas.scss

This PR is to remove the `pointer-events: auto` from the selector `.form-control[data-input][disabled], .form-control[data-textarea][disabled]` since it's not needed.

ROU-11631: Input and Textarea do not allow the text to be selected when the component is disabled V2

---

src/scripts/OSFramework/OSUI/Helper/Device.ts

- To keep our code base modern and updated we need to revisit the list of supported iPhone sizes used for adding the CSS class `iphonex`.
- Added all iPhone 15 and 16 devices to the list of iPhone devices with the associated resolutions
1. Open an app on an iPhone 15 or 16
2. Check that the `iphonex` is present

ROU-11663: Added iPhone 15 and 16 to iPhone devices list

---

src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts

This PR is for fixing keyboard interaction feedback of the DropdownServerSideItem; 
- when the keyboard was used to select dropdownItem two events were fired, one by the item that was unselected, and other by the selected item.
- don't trigger callback of the unselected option item, since it will be called by the new option item select.
1. Go to sample 
2. Open Console
3. Using keyboard navigation navigate/select between items 
4. Lock to the console and check that there aren’t 2 values return at the same timestamp

ROU-11773: DropdownServerSideItem: OnSelected Event Fires Twice When Using Keyboard

---

src/scripts/OSFramework/OSUI/Pattern/Progress/Bar/ProgressBar.ts
src/scripts/OSFramework/OSUI/Pattern/Progress/Circle/ProgressCircle.ts

This PR is for fixing a small TypeScript type error. No effect in runtime.
- There was a warning in typescript compilation
- Changed the type from `unknown` to `JSON`

ROU-11743: Fixing type in TypeScript

---

src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss
src/scripts/OSFramework/OSUI/Pattern/MonthPicker/scss/_monthpicker.scss
src/scripts/Providers/OSUI/SharedProviderResources/Flatpickr/scss/_flatpickr.scss

- When using inline mode through extensibility, there were some UI issues:
- The year input was not displayed for the Date Picker, Date Picker Range, and Month Picker
- The week numbers were shrunk 
- When opening a date and time-related picker above an inline version, we could see the arrows from the inline version below
- Added specific rules for `.inline` mode.  
1. Go to a screen with Date Pickers, Date Pickers Range, Month Pickers, and Time Pickers, with and without inline mode
2. Check that all the UI and functionalities are now working
3. Validate with RTL enabled
- Before fix: 
- After fix: 
-   [ ] …

ROU-11799: Fix inline date and month picker visual issues

---

package.json
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is to update the VirtualSelect library to the latest version **v1.0.49**
- Updated Virtual Select provider to **v1.0.49**

ROU-11808: Update Virtual Select provider to v1.0.49

---

src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Search/VirtualSelectSearch.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Search/VirtualSelectSearchConfig.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Tags/VirtualSelectTags.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Tags/VirtualSelectTagsConfig.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/VirtualSelect.d.ts

This PR will change the way **DropdownSearch** and **DropdownTags** `aria-label` value attribute is being set.
- `aria-label` attribute was being changed by changing it's value directly.
- The previous approach didn't take consideration on the `ariaLabelText` library (VirtualSelect) attribute;
- `setHiddenInputWrapperAriaLabelVal()` method has been deprecated **deprecated**.
- Updated the way expected tests to be added as `aria-label` are being set, by using the provider property.
-   [  ] requires changes in OutSystems (if so, provide a module with changes)
-   [  ] requires new sample page in OutSystems (if so, provide a module with changes)

ROU-11784: Review how ariaLabel is being set to the DropdownSearch and DropdownTags

---

src/scripts/OSFramework/OSUI/ErrorCodes.ts
src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts

- By design, the Tabs component requires having at least one TabsHeaderItem/TabsContentItem, but we were not handling this, and an error was thrown: 
- Made more visible the error message if the user is trying to use the Tabs without any content or a header item without being too intrusive, ie, logging a warning message in the console but throwing an error.
1. Go to a screen with Tabs without TabsHeaderItem/TabsContentItem
2. Check that no error is thrown and that in the console we can see a `console.log` with the message `OSUI-GEN-09007: To ensure predictable behavior and avoid runtime issues, the Tabs component under uniqueId: '0.3kyrdmk6pa'  is designed to include at least one TabsHeaderItem and one TabsContentItem.`
-   [X] clean all …

ROU-11858: Improve error handling for scenarios without TabsHeaderItem/TabsContentItem

---

src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts

This PR is for adding extra validation in the method `_handleKeypressEvent` to avoid having errors being thrown that are already handled, even though this would occur in an unexpected scenario

ROU-11858: Improve error handling on Tabs

---

src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts

This PR is for...
[Sample page](https://outsystemsui-dev.outsystemsenterprise.com/TaskSample_DEV_ROU11864/TabsChangeRuntime?_ts=638817884920100380)
- Hiding a Header Item that was active or not could cause a visual desynchronization of the tab indicator and the position of the currently active tab.
- Used the Helper AsyncInvocation function to ensure that the tab indicator update occurs only after the Tab Header item has been completely removed.
- Moved the tab indicator update outside of the if condition that checks whether the removed Header item was active since we want to update the tab indicator regardless of that condition.
1. Select the First Tab;
2. Hide Header 1 using the toggle on top of the page;
3. Check that the tab indicator is correctly placed below the the tab that is now …

ROU-11864: Fix tab indicator incorrect positioning

---

README.md
gulp/ProjectSpecs/DefaultSpecs.js
package.json
src/scripts/OSFramework/OSUI/Constants.ts
src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/AnimatedLabel.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect.scss
src/scss/O11.OutSystemsUI.scss
src/scss/ODC.OutSystemsUI.scss

- Incremented version to `2.24.0`
- Added styles for Dropdown Search and Tags for the case where we use the extensibility property `allowNewOption`
- Fixed two lint warnings in the AnimatedLabels
1. Go to the DropdownSearch test page
2. Go to the “Extensibility Features” section
3. Select the `allowNewOption = true`
4. Click on Apply
5. Type “Joe“
6. Check that the + icon now has the primary color
7. Repeat it in the DropdownTags test page
-   [ ] requires changes in OutSystems
-   [ ] requires new sample page in OutSystems

ROU-11919: Increment version and add styles for dropdowns

---

src/scripts/OSFramework/OSUI/Behaviors/FocusTrap.ts

This PR will fix a regression issue at the focus trap.
- After changes made in an issue was added that is preventing FocusTrap to occurs.
- Added the call to _setCallbacks() into the constructor to ensure focus trap event handler callbacks are set up before use.

ROU-12066: FocusTrap - Initialize focus trap callbacks in constructor

---

src/scripts/OSFramework/OSUI/Pattern/BottomSheet/BottomSheet.ts

- When entering on an iPad Pro in landscape and refreshing the screen, gestures were not working.
- Added missing validation on BottomSheet
1. Go to a screen with BottomSheet on an iPad Pro in landscape
2. Refresh the screen
3. Check that gestures are working now.

ROU-12062: Add missing validation on BottomSheet

---

src/scripts/OSFramework/OSUI/Behaviors/FocusTrap.ts
src/scripts/OSFramework/OSUI/GlobalEnum.ts
src/scripts/OSFramework/OSUI/Helper/ManageAccessibility.ts
src/scripts/OSFramework/OSUI/Pattern/BottomSheet/BottomSheet.ts
src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/scss/_overflowmenu.scss

This PR will fix A11Y keyboard navigation issue under the context of SideBar and BottomSheet.
- When keyboard navigation (A11Y) was in use inside SideBar/BottomSheet, containing any other type of OSUI components that has to manage their own focusable elements, the navigation process was broken.
- This was happening because we were updating `tabindex="-1"` into `tabindex="0"` no matter where the element with this attribute is/belongs.
- Added the logic to just affect the update of the `tabindex="-1"` elements on the first layer of SideBar/BottomSheet children.
- From now on, components inside of this both elements will maintain their default keyboard navigation.
- This will also fix a layer issue on the OverflowMenu balloon since it was being behind the DropdownTags when combined in the …

ROU-12091: Sidebar/BottomSheet - Incorrect keyboard navigation on several widgets

---

package.json
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is to update the VirtualSelect library to the latest version **v1.1.0**
- Updated Virtual Select provider to **v1.1.0**

ROU-11920: Update Virtual Select to v1.1.0

---

package.json
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss

This PR is to update the VirtualSelect library to the latest pre-release **v1.1.2**
- Updated Virtual Select provider to the latest pre-release **v1.1.2**
- _Note:_  couldn’t create an npm since the GH failed for permission, and [this](https://github.com/OutSystems/outsystems-ui/blob/b207c90e3391e7030e3e252a8b53ee34f53a609e/package.json#L70 ) will be outdated   

ROU-12253: Update Virtual Select to v1.1.2
